In [12]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

In [13]:
# 1. Manually list your 6 files
csv_files = [
    "data/2021-atp-season.csv",
    "data/2022-atp-season.csv",
    "data/2023-atp-season.csv",
    "data/2024-atp-season.csv",
    "data/2025-atp-season.csv",
    "data/2026-atp-season.csv",
]

# 2. Read and combine them
df = pd.concat((pd.read_csv(file) for file in csv_files))

In [14]:
df.to_csv("ATP-all_seasons.csv", index=False)

In [15]:
df.describe()

,match_id,season_year,tour_type,date_timestamp,surface_id,home_id,away_id,home_rank,away_rank,home_points,...,home_double_faults,away_double_faults,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc
count,7.784800e+04,77848.000000,77848.000000,7.784800e+04,77848.000000,77848.000000,77848.000000,53236.000000,53201.000000,53236.000000,...,76681.000000,76681.000000,76676.000000,76676.000000,76676.000000,76676.000000,76247.000000,76175.000000,76175.000000,76247.000000
mean,5.505716e+07,2023.598423,2.383619,1.705714e+09,1.573438,548944.406754,548659.963403,253.786573,263.092291,678.946747,...,2.872433,2.891942,61.847097,61.216691,38.349249,37.710587,41.557282,40.760316,54.480288,54.288613
std,2.601817e+07,1.632953,0.925887,5.091210e+07,0.621508,258744.403182,258605.244790,248.635889,255.723109,1262.978306,...,2.336802,2.318432,10.465028,10.440741,9.987705,9.926976,25.835706,26.332733,27.554773,26.849353
min,1.000501e+07,2021.000000,1.000000,1.609859e+09,1.000000,100315.000000,100315.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.239619e+07,2022.000000,1.000000,1.662126e+09,1.000000,328410.000000,326801.000000,91.000000,97.000000,155.000000,...,1.000000,1.000000,56.000000,55.000000,32.000000,31.000000,25.000000,25.000000,40.000000,40.000000
50%,5.512570e+07,2024.000000,3.000000,1.708372e+09,2.000000,563621.000000,563301.000000,199.000000,202.000000,299.000000,...,2.000000,2.000000,62.000000,62.000000,38.000000,38.000000,40.000000,40.000000,57.000000,57.000000
75%,7.766596e+07,2025.000000,3.000000,1.750754e+09,2.000000,771934.000000,771934.000000,327.000000,336.000000,684.000000,...,4.000000,4.000000,69.000000,68.000000,45.000000,44.000000,57.000000,56.000000,72.727273,71.000000
max,9.999594e+07,2026.000000,5.000000,1.788361e+09,4.000000,999630.000000,999630.000000,2258.000000,2278.000000,14700.000000,...,26.000000,23.000000,100.000000,100.000000,325.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [16]:
df.isnull().sum()

match_id                            0
season_year                         0
tour_type                           0
tour_type_human                     0
date_timestamp                      0
date_human                          0
tournament                          0
round                            1263
surface                             0
surface_id                          0
status                              0
status_extra                        0
home_name                           0
away_name                           0
home_id                             0
away_id                             0
home_rank                       24612
away_rank                       24647
home_points                     24612
away_points                     24647
winner_code                       576
home_set_score                    962
away_set_score                    962
home_set_1_score                  962
away_set_1_score                  962
home_set_2_score                 1530
away_set_2_score                 1530
home_set_3_score                49696
away_set_3_score                49696
home_set_4_score                76141
away_set_4_score                76141
home_set_5_score                77201
away_set_5_score                77201
home_odds_match_winner           3286
away_odds_match_winner           3286
home_odds_first_set_winner       5677
away_odds_first_set_winner       5677
home_aces                        1167
away_aces                        1167
home_double_faults               1167
away_double_faults               1167
home_service_points_won_perc     1172
away_service_points_won_perc     1172
home_return_points_won_perc      1172
away_return_points_won_perc      1172
home_break_points_won_perc       1601
away_break_points_won_perc       1673
home_break_points_saved_perc     1673
away_break_points_saved_perc     1601
dtype: int64

In [17]:
df.nunique()

match_id                        77848
season_year                         6
tour_type                           3
tour_type_human                     3
date_timestamp                  60769
date_human                       1964
tournament                       1020
round                              10
surface                             4
surface_id                          4
status                              2
status_extra                        6
home_name                        2709
away_name                        2705
home_id                          2719
away_id                          2710
home_rank                        1527
away_rank                        1557
home_points                      2439
away_points                      2387
winner_code                         2
home_set_score                      4
away_set_score                      4
home_set_1_score                   17
away_set_1_score                   14
home_set_2_score                   15
away_set_2_score                   14
home_set_3_score                   17
away_set_3_score                   19
home_set_4_score                   14
away_set_4_score                   13
home_set_5_score                   11
away_set_5_score                   11
home_odds_match_winner            379
away_odds_match_winner            406
home_odds_first_set_winner        307
away_odds_first_set_winner        331
home_aces                          46
away_aces                          49
home_double_faults                 27
away_double_faults                 24
home_service_points_won_perc       86
away_service_points_won_perc       86
home_return_points_won_perc        87
away_return_points_won_perc        86
home_break_points_won_perc        155
away_break_points_won_perc        159
home_break_points_saved_perc      159
away_break_points_saved_perc      156
dtype: int64

In [18]:
df.columns.tolist()

['match_id',
 'season_year',
 'tour_type',
 'tour_type_human',
 'date_timestamp',
 'date_human',
 'tournament',
 'round',
 'surface',
 'surface_id',
 'status',
 'status_extra',
 'home_name',
 'away_name',
 'home_id',
 'away_id',
 'home_rank',
 'away_rank',
 'home_points',
 'away_points',
 'winner_code',
 'home_set_score',
 'away_set_score',
 'home_set_1_score',
 'away_set_1_score',
 'home_set_2_score',
 'away_set_2_score',
 'home_set_3_score',
 'away_set_3_score',
 'home_set_4_score',
 'away_set_4_score',
 'home_set_5_score',
 'away_set_5_score',
 'home_odds_match_winner',
 'away_odds_match_winner',
 'home_odds_first_set_winner',
 'away_odds_first_set_winner',
 'home_aces',
 'away_aces',
 'home_double_faults',
 'away_double_faults',
 'home_service_points_won_perc',
 'away_service_points_won_perc',
 'home_return_points_won_perc',
 'away_return_points_won_perc',
 'home_break_points_won_perc',
 'away_break_points_won_perc',
 'home_break_points_saved_perc',
 'away_break_points_saved_perc']

In [9]:
df = df.drop(columns=['tour_type_human', 'date_human', 'surface_id'])

In [19]:
report = ProfileReport(df)

In [20]:
report

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 49/49 [00:00<00:00, 49.54it/s]

KeyboardInterrupt:

In [21]:
df.groupby("season_year").size()

season_year
2021    10193
2022    12914
2023    13691
2024    14322
2025    14620
2026    12108
dtype: int64

In [22]:
df["status"].value_counts(dropna=False)

status
FINISHED     77746
SCHEDULED      102
Name: count, dtype: int64

In [24]:
df["status_extra"].value_counts(dropna=False)

status_extra
FINISHED     74307
RETIRED       2569
CANCELED       469
WALKOVER       390
SCHEDULED      102
AWARDED         11
Name: count, dtype: int64

In [25]:
pd.crosstab(
    df["status"],
    df["winner_code"],
    dropna=False
)

winner_code    1.0    2.0  NaN
status
FINISHED     40065  37207  474
SCHEDULED        0      0  102

In [26]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100
})

missing_summary = (
    missing_summary[
        missing_summary["missing_count"] > 0
    ]
    .sort_values("missing_pct", ascending=False)
)

missing_summary

                              missing_count  missing_pct
away_set_5_score                      77201    99.168893
home_set_5_score                      77201    99.168893
home_set_4_score                      76141    97.807265
away_set_4_score                      76141    97.807265
home_set_3_score                      49696    63.837221
away_set_3_score                      49696    63.837221
away_rank                             24647    31.660415
away_points                           24647    31.660415
home_points                           24612    31.615456
home_rank                             24612    31.615456
home_odds_first_set_winner             5677     7.292416
away_odds_first_set_winner             5677     7.292416
away_odds_match_winner                 3286     4.221046
home_odds_match_winner                 3286     4.221046
home_break_points_saved_perc           1673     2.149060
away_break_points_won_perc             1673     2.149060
home_break_points_won_perc             1601     2.056572
away_break_points_saved_perc           1601     2.056572
away_set_2_score                       1530     1.965368
home_set_2_score                       1530     1.965368
round                                  1263     1.622392
home_service_points_won_perc           1172     1.505498
away_service_points_won_perc           1172     1.505498
home_return_points_won_perc            1172     1.505498
away_return_points_won_perc            1172     1.505498
home_aces                              1167     1.499075
away_aces                              1167     1.499075
home_double_faults                     1167     1.499075
away_double_faults                     1167     1.499075
away_set_1_score                        962     1.235741
home_set_1_score                        962     1.235741
away_set_score                          962     1.235741
home_set_score                          962     1.235741
winner_code                             576     0.739903

## Building Primitive Model

In [27]:
# Create our modeling population
completed_matches = df[
    (df["status"] == "FINISHED") &
    (df["status_extra"] == "FINISHED") &
    (df["winner_code"].notna())
].copy()

In [28]:
completed_matches.size

3640896

In [29]:
completed_matches["home_win"] = (
    completed_matches["winner_code"] == 1
).astype(int)

In [30]:
completed_matches["home_win"].value_counts()

home_win
1    38587
0    35717
Name: count, dtype: int64

## Building baseline

In [31]:
baseline = completed_matches.dropna(
    subset=["home_rank", "away_rank"]
).copy()

In [32]:
baseline.head(10)

,match_id,season_year,tour_type,tour_type_human,date_timestamp,date_human,tournament,round,surface,surface_id,...,away_double_faults,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win
28,76655088,2021,1,ATP Tour,1610009400,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,1.0,60.0,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1
30,37915000,2021,1,ATP Tour,1610013300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,3.0,69.0,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1
31,59286256,2021,1,ATP Tour,1610016300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,0.0,80.0,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1
33,42175550,2021,1,ATP Tour,1610017500,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,2.0,58.0,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0
34,77512211,2021,1,ATP Tour,1610020800,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,1.0,51.0,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0
35,30910475,2021,1,ATP Tour,1610021700,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,3.0,54.0,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0
36,30200362,2021,1,ATP Tour,1610036100,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,1.0,54.0,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0
37,37109764,2021,1,ATP Tour,1610041200,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,4.0,66.0,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1
38,36281527,2021,1,ATP Tour,1610048400,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,4.0,67.0,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1
39,24205146,2021,1,ATP Tour,1610061000,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,1.0,66.0,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0

In [33]:
baseline["predicted_home_win"] = (
    baseline["home_rank"] < baseline["away_rank"]
).astype(int)

In [34]:
baseline.head(10)

,match_id,season_year,tour_type,tour_type_human,date_timestamp,date_human,tournament,round,surface,surface_id,...,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win,predicted_home_win
28,76655088,2021,1,ATP Tour,1610009400,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,60.0,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1,1
30,37915000,2021,1,ATP Tour,1610013300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,69.0,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1,0
31,59286256,2021,1,ATP Tour,1610016300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,80.0,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1,0
33,42175550,2021,1,ATP Tour,1610017500,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,58.0,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0,0
34,77512211,2021,1,ATP Tour,1610020800,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,51.0,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0,0
35,30910475,2021,1,ATP Tour,1610021700,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,54.0,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0,1
36,30200362,2021,1,ATP Tour,1610036100,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,54.0,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0,0
37,37109764,2021,1,ATP Tour,1610041200,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,66.0,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1,1
38,36281527,2021,1,ATP Tour,1610048400,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,67.0,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1,1
39,24205146,2021,1,ATP Tour,1610061000,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,66.0,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0,1

In [35]:
from sklearn.metrics import accuracy_score

baseline_accuracy = accuracy_score(
    baseline["home_win"],
    baseline["predicted_home_win"]
)

print(f"The baseline accuracy score is: {baseline_accuracy*100}%")

The baseline accuracy score is: 62.54329539831767%

## Logistic Regression Model V1

In [36]:
model_data = completed_matches.copy()

model_data["rank_diff"] = (
    model_data["away_rank"] - model_data["home_rank"]
)

model_data["points_diff"] = (
    model_data["home_points"] - model_data["away_points"]
)

In [37]:
model_data[
    [
        "home_name",
        "away_name",
        "home_rank",
        "away_rank",
        "rank_diff",
        "home_points",
        "away_points",
        "points_diff",
        "home_win"
    ]
].head(50)

,home_name,away_name,home_rank,away_rank,rank_diff,home_points,away_points,points_diff,home_win
0,Galovic V.,Dougaz A.,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Sakamoto P.,Young D.,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Escobar G.,Quiroz R.,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Barrios Vera T.,Harrison C.,NaN,NaN,NaN,NaN,NaN,NaN,0
6,Oliveira G.,Draxl L.,NaN,NaN,NaN,NaN,NaN,NaN,1
7,Lock B.,King K.,NaN,NaN,NaN,NaN,NaN,NaN,0
8,Kavcic B.,Tokac T.,NaN,NaN,NaN,NaN,NaN,NaN,1
9,Ortega-Olmedo R.,Vavassori A.,NaN,NaN,NaN,NaN,NaN,NaN,0
10,Golubev A.,Molcan A.,NaN,NaN,NaN,NaN,NaN,NaN,0
11,Andreev A.,Klein L.,NaN,NaN,NaN,NaN,NaN,NaN,1
12,Pellegrino A.,Aksu C.,NaN,NaN,NaN,NaN,NaN,NaN,1
13,Sachko V.,Vrbensky M.,NaN,NaN,NaN,NaN,NaN,NaN,0
14,Krstin P.,Turker M. N.,NaN,NaN,NaN,NaN,NaN,NaN,0
15,Bachinger M.,Orlov V.,NaN,NaN,NaN,NaN,NaN,NaN,1
16,Heliovaara H.,Sasikumar M.,NaN,NaN,NaN,NaN,NaN,NaN,1
17,Basic M.,Kuzmanov D.,NaN,NaN,NaN,NaN,NaN,NaN,0
19,Lazarov A.,Miedler L.,NaN,NaN,NaN,NaN,NaN,NaN,0
20,Galovic V.,Quiroz R.,NaN,NaN,NaN,NaN,NaN,NaN,0
21,Young D.,Kozlov S.,NaN,NaN,NaN,NaN,NaN,NaN,1
22,Harrison C.,Khan Z.,NaN,NaN,NaN,NaN,NaN,NaN,1
23,Oliveira G.,King K.,NaN,NaN,NaN,NaN,NaN,NaN,0
24,Kavcic B.,Molcan A.,NaN,NaN,NaN,NaN,NaN,NaN,0
25,Turker M. N.,Vrbensky M.,NaN,NaN,NaN,NaN,NaN,NaN,0
26,Pellegrino A.,Kuzmanov D.,NaN,NaN,NaN,NaN,NaN,NaN,0
27,Vavassori A.,Andreev A.,NaN,NaN,NaN,NaN,NaN,NaN,0
28,Basilashvili N.,Arnaboldi A.,40.0,267.0,227.0,1395.0,206.0,1189.0,1
29,Kotov P.,Heliovaara H.,NaN,NaN,NaN,NaN,NaN,NaN,1
30,Celikbilek A.,Zuk K.,309.0,262.0,-47.0,150.0,209.0,-59.0,1
31,Ruusuvuori E.,Vesely J.,87.0,67.0,-20.0,806.0,928.0,-122.0,1
32,Bachinger M.,Miedler L.,NaN,NaN,NaN,NaN,NaN,NaN,1
33,Caruso S.,Bublik A.,76.0,49.0,-27.0,858.0,1090.0,-232.0,0
34,Herbert P.,Goffin D.,83.0,16.0,-67.0,822.0,2555.0,-1733.0,0
35,Kecmanovic M.,Travaglia S.,42.0,75.0,33.0,1328.0,869.0,459.0,0
36,Bellucci T.,Monteiro T.,281.0,84.0,-197.0,185.0,820.0,-635.0,0
37,Paul T.,Nam Ji S.,52.0,268.0,216.0,1080.0,205.0,875.0,1
38,Mager G.,Harrison R.,101.0,481.0,380.0,733.0,73.0,660.0,1
39,Kwon S.,Korda S.,95.0,119.0,24.0,768.0,566.0,202.0,0
40,McDonald M.,Querrey S.,194.0,56.0,-138.0,335.0,1065.0,-730.0,0
41,Kotov P.,Struff J-L.,269.0,37.0,-232.0,205.0,1450.0,-1245.0,0
42,Lamasine T.,Gerasimov E.,271.0,78.0,-193.0,204.0,840.0,-636.0,1
43,Andreev A.,Ilhan M.,564.0,571.0,7.0,52.0,51.0,1.0,1
44,Molcan A.,Grenier H.,313.0,250.0,-63.0,145.0,220.0,-75.0,0
45,Chardy J.,Albot R.,72.0,85.0,13.0,880.0,817.0,63.0,1
46,Berrettini M.,Kirkin E.,10.0,446.0,436.0,3085.0,83.0,3002.0,1
47,Jaziri M.,De Minaur A.,249.0,23.0,-226.0,220.0,1860.0,-1640.0,0
49,Fognini F.,Vrbensky M.,17.0,311.0,294.0,2400.0,148.0,2252.0,1
51,Etcheverry T. M.,Harrison C.,256.0,789.0,533.0,216.0,22.0,194.0,0
52,Galan D. E.,Martin A.,115.0,100.0,-15.0,606.0,734.0,-128.0,1
53,Rubin N.,Quiroz R.,251.0,293.0,42.0,219.0,171.0,48.0,0
54,Fratangelo B.,King K.,274.0,304.0,30.0,195.0,154.0,41.0,1

In [38]:
model_data[
    ["home_rank", "away_rank", "home_points", "away_points"]
].isna().mean() * 100

home_rank      31.501669
away_rank      31.546081
home_points    31.501669
away_points    31.546081
dtype: float64

In [39]:
v1_data = model_data.dropna(
    subset=[
        "home_rank",
        "away_rank",
        "home_points",
        "away_points"
    ]
).copy()

In [40]:
print("Original completed matches:", len(model_data))
print("V1 usable matches:", len(v1_data))
print(
    "Percentage retained:",
    len(v1_data) / len(model_data) * 100
)

Original completed matches: 74304
V1 usable matches: 50525
Percentage retained: 67.99768518518519

In [41]:
# Splitting the data
train_v1 = v1_data[
    v1_data["season_year"] <= 2024
].copy()

validation_v1 = v1_data[
    v1_data["season_year"] == 2025
].copy()

In [42]:
train_v1.head(10)

,match_id,season_year,tour_type,tour_type_human,date_timestamp,date_human,tournament,round,surface,surface_id,...,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win,rank_diff,points_diff
28,76655088,2021,1,ATP Tour,1610009400,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1,227.0,1189.0
30,37915000,2021,1,ATP Tour,1610013300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1,-47.0,-59.0
31,59286256,2021,1,ATP Tour,1610016300,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1,-20.0,-122.0
33,42175550,2021,1,ATP Tour,1610017500,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0,-27.0,-232.0
34,77512211,2021,1,ATP Tour,1610020800,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0,-67.0,-1733.0
35,30910475,2021,1,ATP Tour,1610021700,07 Jan 2021,Antalya ATP,1/16-finals,hard,1,...,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0,33.0,459.0
36,30200362,2021,1,ATP Tour,1610036100,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0,-197.0,-635.0
37,37109764,2021,1,ATP Tour,1610041200,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1,216.0,875.0
38,36281527,2021,1,ATP Tour,1610048400,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1,380.0,660.0
39,24205146,2021,1,ATP Tour,1610061000,07 Jan 2021,Delray Beach ATP,1/16-finals,hard,1,...,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0,24.0,202.0

In [43]:
# Checking the size of the training and validation data sets
print("Training data: ", len(train_v1))
print("Validation data: ", len(validation_v1))

Training data:  30832
Validation data:  8999

In [44]:
print(train_v1["season_year"].value_counts().sort_index())
print()
print(validation_v1["season_year"].value_counts().sort_index())

season_year
2021    6623
2022    7722
2023    8111
2024    8376
Name: count, dtype: int64

season_year
2025    8999
Name: count, dtype: int64

In [45]:
# Defining the covariates and response
features_v1 = ["rank_diff", "points_diff"]

X_train = train_v1[features_v1]
y_train = train_v1["home_win"]

X_val = validation_v1[features_v1]
y_val = validation_v1["home_win"]

In [46]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train shape: (30832, 2)
y_train shape: (30832,)
X_val shape: (8999, 2)
y_val shape: (8999,)

In [47]:
X_train.head()

    rank_diff  points_diff
28      227.0       1189.0
30      -47.0        -59.0
31      -20.0       -122.0
33      -27.0       -232.0
34      -67.0      -1733.0

In [57]:
# Fitting the logistic model
from sklearn.linear_model import LogisticRegression

log_reg_v1 = LogisticRegression(max_iter=2000)

log_reg_v1.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [58]:
print("Intercept:", log_reg_v1.intercept_[0])

for feature, coefficient in zip(
    features_v1,
    log_reg_v1.coef_[0]
):
    print(feature, ":", coefficient)

Intercept: 6.837326526350055e-07
rank_diff : 0.001971020174479783
points_diff : 0.00032663996633854416

In [59]:
# Predictions made by our model
val_predictions = log_reg_v1.predict(X_val)

In [60]:
# The prediction probabilites
val_probabilities = log_reg_v1.predict_proba(X_val)[:, 1]

In [61]:
print("The value predictions for the first 10 observations: ", val_predictions[:10])
print("The value probabilities for the first 10 observations: ", val_probabilities[:10])

The value predictions for the first 10 observations:  [1 1 1 1 1 1 0 1 1 1]
The value probabilities for the first 10 observations:  [0.59164014 0.57896765 0.80351223 0.60958457 0.70116809 0.78635222
 0.29878953 0.9315902  0.72122947 0.5290016 ]

In [62]:
# Calculating the accuracy score
from sklearn.metrics import accuracy_score

v1_accuracy = accuracy_score(
    y_val,
    val_predictions
)

print("Logistic Regression V1 Accuracy:", round(v1_accuracy*100, 2), "%")

Logistic Regression V1 Accuracy: 62.72 %

In [63]:
from sklearn.metrics import log_loss

v1_log_loss = log_loss(
    y_val,
    val_probabilities
)

print("Logistic Regression V1 Log Loss:", v1_log_loss)

Logistic Regression V1 Log Loss: 0.6466771797539345

## Logistic Regression V2
- This model will use the player's previous performance as the covariates
- The performance in this case would be the average of the ace points, win rates, difference in the games within winning sets, average of points lost due to double faults.

In [95]:
# Creating the history for the home player
home_history = completed_matches[[
    "match_id",
    "date_timestamp",
    "season_year",
    "surface",
    "home_id",
    "home_name",
    "away_id",
    "away_name",
    "winner_code",
    "home_aces",
    "home_double_faults",
    "home_service_points_won_perc",
    "home_return_points_won_perc",
    "home_break_points_won_perc",
    "home_break_points_saved_perc"
]].copy()

In [96]:
home_history = home_history.rename(columns={
    "home_id": "player_id",
    "home_name": "player_name",
    "away_id": "opponent_id",
    "away_name": "opponent_name",
    "home_aces": "aces",
    "home_double_faults": "double_faults",
    "home_service_points_won_perc": "service_points_won_perc",
    "home_return_points_won_perc": "return_points_won_perc",
    "home_break_points_won_perc": "break_points_won_perc",
    "home_break_points_saved_perc": "break_points_saved_perc"
})

In [97]:
home_history["won"] = (
    home_history["winner_code"] == 1
).astype(int)

In [98]:
home_history.head(50)

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4,20264415,1609870500,2021,hard,376007,Barrios Vera T.,884091,Harrison C.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
6,60708459,1609879800,2021,hard,303110,Oliveira G.,806525,Draxl L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
7,16746158,1609887000,2021,hard,132962,Lock B.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
8,92238253,1609923000,2021,hard,276062,Kavcic B.,494292,Tokac T.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
9,89146752,1609923600,2021,hard,287612,Ortega-Olmedo R.,489220,Vavassori A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
10,74669820,1609925400,2021,hard,502076,Golubev A.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
11,71170975,1609927500,2021,hard,598150,Andreev A.,505077,Klein L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
12,30711940,1609927800,2021,hard,273580,Pellegrino A.,996327,Aksu C.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
13,72595040,1609928400,2021,hard,626903,Sachko V.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
14,32846556,1609930800,2021,hard,372643,Krstin P.,426933,Turker M. N.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
15,39551039,1609933800,2021,hard,164915,Bachinger M.,200057,Orlov V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
16,67392456,1609934400,2021,hard,338721,Heliovaara H.,966030,Sasikumar M.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
17,54035930,1609934400,2021,hard,527695,Basic M.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
19,89913477,1609938300,2021,hard,783429,Lazarov A.,810765,Miedler L.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
20,53269779,1609949100,2021,hard,479435,Galovic V.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
21,89813135,1609950000,2021,hard,186820,Young D.,649763,Kozlov S.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
22,42200729,1609955400,2021,hard,884091,Harrison C.,846957,Khan Z.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
23,91215092,1609966200,2021,hard,303110,Oliveira G.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
24,59537670,1610003100,2021,hard,276062,Kavcic B.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
25,55206216,1610003400,2021,hard,426933,Turker M. N.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
26,63761082,1610003400,2021,hard,273580,Pellegrino A.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
27,80589723,1610004000,2021,hard,489220,Vavassori A.,598150,Andreev A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
28,76655088,1610009400,2021,hard,309924,Basilashvili N.,659274,Arnaboldi A.,1.0,3.0,4.0,60.0,46.0,35.0,20.0,1
29,36126999,1610011500,2021,hard,627199,Kotov P.,338721,Heliovaara H.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
30,37915000,1610013300,2021,hard,368199,Celikbilek A.,822730,Zuk K.,1.0,4.0,4.0,69.0,35.0,29.0,90.0,1
31,59286256,1610016300,2021,hard,384119,Ruusuvuori E.,191042,Vesely J.,1.0,1.0,0.0,80.0,29.0,50.0,0.0,1
32,64520760,1610016600,2021,hard,164915,Bachinger M.,810765,Miedler L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
33,42175550,1610017500,2021,hard,474240,Caruso S.,732840,Bublik A.,2.0,0.0,3.0,58.0,25.0,0.0,63.0,0
34,77512211,1610020800,2021,hard,321867,Herbert P.,811823,Goffin D.,2.0,7.0,4.0,51.0,44.0,71.0,58.0,0
35,30910475,1610021700,2021,hard,692911,Kecmanovic M.,944674,Travaglia S.,2.0,3.0,2.0,54.0,39.0,100.0,44.0,0
36,30200362,1610036100,2021,hard,632715,Bellucci T.,261646,Monteiro T.,2.0,3.0,3.0,54.0,34.0,11.0,33.0,0
37,37109764,1610041200,2021,hard,650985,Paul T.,315309,Nam Ji S.,1.0,5.0,0.0,66.0,49.0,67.0,67.0,1
38,36281527,1610048400,2021,hard,528890,Mager G.,239088,Harrison R.,1.0,9.0,3.0,67.0,39.0,50.0,92.0,1
39,24205146,1610061000,2021,hard,614106,Kwon S.,261903,Korda S.,2.0,4.0,4.0,66.0,39.0,17.0,25.0,0
40,61718845,1610068200,2021,hard,476352,McDonald M.,110329,Querrey S.,2.0,4.0,2.0,60.0,33.0,14.0,50.0,0
41,44560846,1610089800,2021,hard,627199,Kotov P.,855008,Struff J-L.,2.0,2.0,1.0,51.0,41.0,29.0,58.0,0
42,82040147,1610089800,2021,hard,981822,Lamasine T.,431960,Gerasimov E.,1.0,0.0,1.0,62.0,45.0,100.0,50.0,1
43,77654561,1610090100,2021,hard,598150,Andreev A.,791393,Ilhan M.,1.0,0.0,0.0,67.0,45.0,67.0,50.0,1
44,96620860,1610091300,2021,hard,583404,Molcan A.,947022,Grenier H.,2.0,3.0,2.0,58.0,35.0,29.0,56.0,0
45,58255115,1610095800,2021,hard,311520,Chardy J.,281568,Albot R.,1.0,5.0,4.0,66.0,52.0,45.0,0.0,1
46,19523148,1610095800,2021,hard,692847,Berrettini M.,117175,Kirkin E.,1.0,8.0,2.0,82.0,51.0,80.0,0.0,1
47,24498577,1610096100,2021,hard,402865,Jaziri M.,284548,De Minaur A.,2.0,3.0,4.0,41.0,19.0,0.0,50.0,0
49,18933339,1610100300,2021,hard,474237,Fognini F.,191513,Vrbensky M.,1.0,0.0,4.0,65.0,44.0,30.0,0.0,1
51,21596449,1610121900,2021,hard,418622,Etcheverry T. M.,884091,Harrison C.,2.0,4.0,3.0,51.0,29.0,33.0,69.0,0
52,46017359,1610127600,2021,hard,613323,Galan D. E.,632445,Martin A.,1.0,3.0,2.0,67.0,44.0,43.0,83.0,1
53,22539845,1610128500,2021,hard,429215,Rubin N.,338092,Quiroz R.,2.0,5.0,6.0,53.0,38.0,75.0,29.0,0
54,50355974,1610133300,2021,hard,849776,Fratangelo B.,130774,King K.,1.0,0.0,0.0,73.0,51.0,67.0,100.0,1

In [87]:
# Creating history for away players
away_history = completed_matches[[
    "match_id",
    "date_timestamp",
    "season_year",
    "surface",
    "home_id",
    "home_name",
    "away_id",
    "away_name",
    "winner_code",
    "home_aces",
    "home_double_faults",
    "home_service_points_won_perc",
    "home_return_points_won_perc",
    "home_break_points_won_perc",
    "home_break_points_saved_perc"
]].copy()

In [88]:
away_history = away_history.rename(columns={
    "home_id": "player_id",
    "home_name": "player_name",
    "away_id": "opponent_id",
    "away_name": "opponent_name",
    "home_aces": "aces",
    "home_double_faults": "double_faults",
    "home_service_points_won_perc": "service_points_won_perc",
    "home_return_points_won_perc": "return_points_won_perc",
    "home_break_points_won_perc": "break_points_won_perc",
    "home_break_points_saved_perc": "break_points_saved_perc"
})

In [99]:
away_history["won"] = (
    away_history["winner_code"] == 2
).astype(int)

In [100]:
away_history.head(50)

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,20264415,1609870500,2021,hard,376007,Barrios Vera T.,884091,Harrison C.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
6,60708459,1609879800,2021,hard,303110,Oliveira G.,806525,Draxl L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
7,16746158,1609887000,2021,hard,132962,Lock B.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
8,92238253,1609923000,2021,hard,276062,Kavcic B.,494292,Tokac T.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
9,89146752,1609923600,2021,hard,287612,Ortega-Olmedo R.,489220,Vavassori A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
10,74669820,1609925400,2021,hard,502076,Golubev A.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
11,71170975,1609927500,2021,hard,598150,Andreev A.,505077,Klein L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
12,30711940,1609927800,2021,hard,273580,Pellegrino A.,996327,Aksu C.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
13,72595040,1609928400,2021,hard,626903,Sachko V.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
14,32846556,1609930800,2021,hard,372643,Krstin P.,426933,Turker M. N.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
15,39551039,1609933800,2021,hard,164915,Bachinger M.,200057,Orlov V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
16,67392456,1609934400,2021,hard,338721,Heliovaara H.,966030,Sasikumar M.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
17,54035930,1609934400,2021,hard,527695,Basic M.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
19,89913477,1609938300,2021,hard,783429,Lazarov A.,810765,Miedler L.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
20,53269779,1609949100,2021,hard,479435,Galovic V.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
21,89813135,1609950000,2021,hard,186820,Young D.,649763,Kozlov S.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
22,42200729,1609955400,2021,hard,884091,Harrison C.,846957,Khan Z.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
23,91215092,1609966200,2021,hard,303110,Oliveira G.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
24,59537670,1610003100,2021,hard,276062,Kavcic B.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
25,55206216,1610003400,2021,hard,426933,Turker M. N.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
26,63761082,1610003400,2021,hard,273580,Pellegrino A.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
27,80589723,1610004000,2021,hard,489220,Vavassori A.,598150,Andreev A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
28,76655088,1610009400,2021,hard,309924,Basilashvili N.,659274,Arnaboldi A.,1.0,3.0,4.0,60.0,46.0,35.0,20.0,0
29,36126999,1610011500,2021,hard,627199,Kotov P.,338721,Heliovaara H.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
30,37915000,1610013300,2021,hard,368199,Celikbilek A.,822730,Zuk K.,1.0,4.0,4.0,69.0,35.0,29.0,90.0,0
31,59286256,1610016300,2021,hard,384119,Ruusuvuori E.,191042,Vesely J.,1.0,1.0,0.0,80.0,29.0,50.0,0.0,0
32,64520760,1610016600,2021,hard,164915,Bachinger M.,810765,Miedler L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
33,42175550,1610017500,2021,hard,474240,Caruso S.,732840,Bublik A.,2.0,0.0,3.0,58.0,25.0,0.0,63.0,1
34,77512211,1610020800,2021,hard,321867,Herbert P.,811823,Goffin D.,2.0,7.0,4.0,51.0,44.0,71.0,58.0,1
35,30910475,1610021700,2021,hard,692911,Kecmanovic M.,944674,Travaglia S.,2.0,3.0,2.0,54.0,39.0,100.0,44.0,1
36,30200362,1610036100,2021,hard,632715,Bellucci T.,261646,Monteiro T.,2.0,3.0,3.0,54.0,34.0,11.0,33.0,1
37,37109764,1610041200,2021,hard,650985,Paul T.,315309,Nam Ji S.,1.0,5.0,0.0,66.0,49.0,67.0,67.0,0
38,36281527,1610048400,2021,hard,528890,Mager G.,239088,Harrison R.,1.0,9.0,3.0,67.0,39.0,50.0,92.0,0
39,24205146,1610061000,2021,hard,614106,Kwon S.,261903,Korda S.,2.0,4.0,4.0,66.0,39.0,17.0,25.0,1
40,61718845,1610068200,2021,hard,476352,McDonald M.,110329,Querrey S.,2.0,4.0,2.0,60.0,33.0,14.0,50.0,1
41,44560846,1610089800,2021,hard,627199,Kotov P.,855008,Struff J-L.,2.0,2.0,1.0,51.0,41.0,29.0,58.0,1
42,82040147,1610089800,2021,hard,981822,Lamasine T.,431960,Gerasimov E.,1.0,0.0,1.0,62.0,45.0,100.0,50.0,0
43,77654561,1610090100,2021,hard,598150,Andreev A.,791393,Ilhan M.,1.0,0.0,0.0,67.0,45.0,67.0,50.0,0
44,96620860,1610091300,2021,hard,583404,Molcan A.,947022,Grenier H.,2.0,3.0,2.0,58.0,35.0,29.0,56.0,1
45,58255115,1610095800,2021,hard,311520,Chardy J.,281568,Albot R.,1.0,5.0,4.0,66.0,52.0,45.0,0.0,0
46,19523148,1610095800,2021,hard,692847,Berrettini M.,117175,Kirkin E.,1.0,8.0,2.0,82.0,51.0,80.0,0.0,0
47,24498577,1610096100,2021,hard,402865,Jaziri M.,284548,De Minaur A.,2.0,3.0,4.0,41.0,19.0,0.0,50.0,1
49,18933339,1610100300,2021,hard,474237,Fognini F.,191513,Vrbensky M.,1.0,0.0,4.0,65.0,44.0,30.0,0.0,0
51,21596449,1610121900,2021,hard,418622,Etcheverry T. M.,884091,Harrison C.,2.0,4.0,3.0,51.0,29.0,33.0,69.0,1
52,46017359,1610127600,2021,hard,613323,Galan D. E.,632445,Martin A.,1.0,3.0,2.0,67.0,44.0,43.0,83.0,0
53,22539845,1610128500,2021,hard,429215,Rubin N.,338092,Quiroz R.,2.0,5.0,6.0,53.0,38.0,75.0,29.0,1
54,50355974,1610133300,2021,hard,849776,Fratangelo B.,130774,King K.,1.0,0.0,0.0,73.0,51.0,67.0,100.0,0

In [101]:
player_history = pd.concat(
    [home_history, away_history],
    ignore_index=True
)

In [102]:
player_history = player_history.sort_values(
    ["date_timestamp", "match_id"]
).reset_index(drop=True)

In [103]:
player_history.shape

(148608, 16)

In [104]:
player_history.head(50)

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
1,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
5,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
6,20264415,1609870500,2021,hard,376007,Barrios Vera T.,884091,Harrison C.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
7,20264415,1609870500,2021,hard,376007,Barrios Vera T.,884091,Harrison C.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
8,60708459,1609879800,2021,hard,303110,Oliveira G.,806525,Draxl L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
9,60708459,1609879800,2021,hard,303110,Oliveira G.,806525,Draxl L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
10,16746158,1609887000,2021,hard,132962,Lock B.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
11,16746158,1609887000,2021,hard,132962,Lock B.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
12,92238253,1609923000,2021,hard,276062,Kavcic B.,494292,Tokac T.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
13,92238253,1609923000,2021,hard,276062,Kavcic B.,494292,Tokac T.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
14,89146752,1609923600,2021,hard,287612,Ortega-Olmedo R.,489220,Vavassori A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
15,89146752,1609923600,2021,hard,287612,Ortega-Olmedo R.,489220,Vavassori A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
16,74669820,1609925400,2021,hard,502076,Golubev A.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
17,74669820,1609925400,2021,hard,502076,Golubev A.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
18,71170975,1609927500,2021,hard,598150,Andreev A.,505077,Klein L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
19,71170975,1609927500,2021,hard,598150,Andreev A.,505077,Klein L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
20,30711940,1609927800,2021,hard,273580,Pellegrino A.,996327,Aksu C.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
21,30711940,1609927800,2021,hard,273580,Pellegrino A.,996327,Aksu C.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
22,72595040,1609928400,2021,hard,626903,Sachko V.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
23,72595040,1609928400,2021,hard,626903,Sachko V.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
24,32846556,1609930800,2021,hard,372643,Krstin P.,426933,Turker M. N.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
25,32846556,1609930800,2021,hard,372643,Krstin P.,426933,Turker M. N.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
26,39551039,1609933800,2021,hard,164915,Bachinger M.,200057,Orlov V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
27,39551039,1609933800,2021,hard,164915,Bachinger M.,200057,Orlov V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
28,54035930,1609934400,2021,hard,527695,Basic M.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
29,54035930,1609934400,2021,hard,527695,Basic M.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
30,67392456,1609934400,2021,hard,338721,Heliovaara H.,966030,Sasikumar M.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
31,67392456,1609934400,2021,hard,338721,Heliovaara H.,966030,Sasikumar M.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
32,89913477,1609938300,2021,hard,783429,Lazarov A.,810765,Miedler L.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
33,89913477,1609938300,2021,hard,783429,Lazarov A.,810765,Miedler L.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
34,53269779,1609949100,2021,hard,479435,Galovic V.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
35,53269779,1609949100,2021,hard,479435,Galovic V.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
36,89813135,1609950000,2021,hard,186820,Young D.,649763,Kozlov S.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
37,89813135,1609950000,2021,hard,186820,Young D.,649763,Kozlov S.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
38,42200729,1609955400,2021,hard,884091,Harrison C.,846957,Khan Z.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
39,42200729,1609955400,2021,hard,884091,Harrison C.,846957,Khan Z.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
40,91215092,1609966200,2021,hard,303110,Oliveira G.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
41,91215092,1609966200,2021,hard,303110,Oliveira G.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
42,59537670,1610003100,2021,hard,276062,Kavcic B.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
43,59537670,1610003100,2021,hard,276062,Kavcic B.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
44,55206216,1610003400,2021,hard,426933,Turker M. N.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
45,55206216,1610003400,2021,hard,426933,Turker M. N.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
46,63761082,1610003400,2021,hard,273580,Pellegrino A.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
47,63761082,1610003400,2021,hard,273580,Pellegrino A.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
48,80589723,1610004000,2021,hard,489220,Vavassori A.,598150,Andreev A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
49,80589723,1610004000,2021,hard,489220,Vavassori A.,598150,Andreev A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1