In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

/Users/chiragkharade/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/var/folders/7t/s00qhkf90sdgwcv66lcjh2x40000gn/T/ipykernel_18511/675270912.py:5: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [3]:
# 1. Manually list your 6 files
csv_files = [
    "data/2021-atp-season.csv",
    "data/2022-atp-season.csv",
    "data/2023-atp-season.csv",
    "data/2024-atp-season.csv",
    "data/2025-atp-season.csv",
    "data/2026-atp-season.csv",
]

# 2. Read and combine them
df = pd.concat((pd.read_csv(file) for file in csv_files))

In [4]:
df.to_csv("ATP-all_seasons.csv", index=False)

In [5]:
df.describe()

,match_id,season_year,tour_type,date_timestamp,surface_id,home_id,away_id,home_rank,away_rank,home_points,...,home_double_faults,away_double_faults,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc
count,7.784800e+04,77848.000000,77848.000000,7.784800e+04,77848.000000,77848.000000,77848.000000,53236.000000,53201.000000,53236.000000,...,76681.000000,76681.000000,76676.000000,76676.000000,76676.000000,76676.000000,76247.000000,76175.000000,76175.000000,76247.000000
mean,5.505716e+07,2023.598423,2.383619,1.705714e+09,1.573438,548944.406754,548659.963403,253.786573,263.092291,678.946747,...,2.872433,2.891942,61.847097,61.216691,38.349249,37.710587,41.557282,40.760316,54.480288,54.288613
std,2.601817e+07,1.632953,0.925887,5.091210e+07,0.621508,258744.403182,258605.244790,248.635889,255.723109,1262.978306,...,2.336802,2.318432,10.465028,10.440741,9.987705,9.926976,25.835706,26.332733,27.554773,26.849353
min,1.000501e+07,2021.000000,1.000000,1.609859e+09,1.000000,100315.000000,100315.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.239619e+07,2022.000000,1.000000,1.662126e+09,1.000000,328410.000000,326801.000000,91.000000,97.000000,155.000000,...,1.000000,1.000000,56.000000,55.000000,32.000000,31.000000,25.000000,25.000000,40.000000,40.000000
50%,5.512570e+07,2024.000000,3.000000,1.708372e+09,2.000000,563621.000000,563301.000000,199.000000,202.000000,299.000000,...,2.000000,2.000000,62.000000,62.000000,38.000000,38.000000,40.000000,40.000000,57.000000,57.000000
75%,7.766596e+07,2025.000000,3.000000,1.750754e+09,2.000000,771934.000000,771934.000000,327.000000,336.000000,684.000000,...,4.000000,4.000000,69.000000,68.000000,45.000000,44.000000,57.000000,56.000000,72.727273,71.000000
max,9.999594e+07,2026.000000,5.000000,1.788361e+09,4.000000,999630.000000,999630.000000,2258.000000,2278.000000,14700.000000,...,26.000000,23.000000,100.000000,100.000000,325.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [6]:
df.isnull().sum()

match_id                            0
season_year                         0
tour_type                           0
tour_type_human                     0
date_timestamp                      0
date_human                          0
tournament                          0
round                            1263
surface                             0
surface_id                          0
status                              0
status_extra                        0
home_name                           0
away_name                           0
home_id                             0
away_id                             0
home_rank                       24612
away_rank                       24647
home_points                     24612
away_points                     24647
winner_code                       576
home_set_score                    962
away_set_score                    962
home_set_1_score                  962
away_set_1_score                  962
home_set_2_score                 1530
away_set_2_score                 1530
home_set_3_score                49696
away_set_3_score                49696
home_set_4_score                76141
away_set_4_score                76141
home_set_5_score                77201
away_set_5_score                77201
home_odds_match_winner           3286
away_odds_match_winner           3286
home_odds_first_set_winner       5677
away_odds_first_set_winner       5677
home_aces                        1167
away_aces                        1167
home_double_faults               1167
away_double_faults               1167
home_service_points_won_perc     1172
away_service_points_won_perc     1172
home_return_points_won_perc      1172
away_return_points_won_perc      1172
home_break_points_won_perc       1601
away_break_points_won_perc       1673
home_break_points_saved_perc     1673
away_break_points_saved_perc     1601
dtype: int64

In [7]:
df.nunique()

match_id                        77848
season_year                         6
tour_type                           3
tour_type_human                     3
date_timestamp                  60769
date_human                       1964
tournament                       1020
round                              10
surface                             4
surface_id                          4
status                              2
status_extra                        6
home_name                        2709
away_name                        2705
home_id                          2719
away_id                          2710
home_rank                        1527
away_rank                        1557
home_points                      2439
away_points                      2387
winner_code                         2
home_set_score                      4
away_set_score                      4
home_set_1_score                   17
away_set_1_score                   14
home_set_2_score                   15
away_set_2_score                   14
home_set_3_score                   17
away_set_3_score                   19
home_set_4_score                   14
away_set_4_score                   13
home_set_5_score                   11
away_set_5_score                   11
home_odds_match_winner            379
away_odds_match_winner            406
home_odds_first_set_winner        307
away_odds_first_set_winner        331
home_aces                          46
away_aces                          49
home_double_faults                 27
away_double_faults                 24
home_service_points_won_perc       86
away_service_points_won_perc       86
home_return_points_won_perc        87
away_return_points_won_perc        86
home_break_points_won_perc        155
away_break_points_won_perc        159
home_break_points_saved_perc      159
away_break_points_saved_perc      156
dtype: int64

In [8]:
df.columns.tolist()

['match_id',
 'season_year',
 'tour_type',
 'tour_type_human',
 'date_timestamp',
 'date_human',
 'tournament',
 'round',
 'surface',
 'surface_id',
 'status',
 'status_extra',
 'home_name',
 'away_name',
 'home_id',
 'away_id',
 'home_rank',
 'away_rank',
 'home_points',
 'away_points',
 'winner_code',
 'home_set_score',
 'away_set_score',
 'home_set_1_score',
 'away_set_1_score',
 'home_set_2_score',
 'away_set_2_score',
 'home_set_3_score',
 'away_set_3_score',
 'home_set_4_score',
 'away_set_4_score',
 'home_set_5_score',
 'away_set_5_score',
 'home_odds_match_winner',
 'away_odds_match_winner',
 'home_odds_first_set_winner',
 'away_odds_first_set_winner',
 'home_aces',
 'away_aces',
 'home_double_faults',
 'away_double_faults',
 'home_service_points_won_perc',
 'away_service_points_won_perc',
 'home_return_points_won_perc',
 'away_return_points_won_perc',
 'home_break_points_won_perc',
 'away_break_points_won_perc',
 'home_break_points_saved_perc',
 'away_break_points_saved_perc']

In [9]:
df = df.drop(columns=['tour_type_human', 'date_human', 'surface_id'])

In [10]:
report = ProfileReport(df)

In [11]:
df.groupby("season_year").size()

season_year
2021    10193
2022    12914
2023    13691
2024    14322
2025    14620
2026    12108
dtype: int64

In [12]:
df["status"].value_counts(dropna=False)

status
FINISHED     77746
SCHEDULED      102
Name: count, dtype: int64

In [13]:
df["status_extra"].value_counts(dropna=False)

status_extra
FINISHED     74307
RETIRED       2569
CANCELED       469
WALKOVER       390
SCHEDULED      102
AWARDED         11
Name: count, dtype: int64

In [14]:
pd.crosstab(
    df["status"],
    df["winner_code"],
    dropna=False
)

winner_code    1.0    2.0  NaN
status
FINISHED     40065  37207  474
SCHEDULED        0      0  102

In [15]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100
})

missing_summary = (
    missing_summary[
        missing_summary["missing_count"] > 0
    ]
    .sort_values("missing_pct", ascending=False)
)

missing_summary

                              missing_count  missing_pct
away_set_5_score                      77201    99.168893
home_set_5_score                      77201    99.168893
home_set_4_score                      76141    97.807265
away_set_4_score                      76141    97.807265
home_set_3_score                      49696    63.837221
away_set_3_score                      49696    63.837221
away_rank                             24647    31.660415
away_points                           24647    31.660415
home_points                           24612    31.615456
home_rank                             24612    31.615456
home_odds_first_set_winner             5677     7.292416
away_odds_first_set_winner             5677     7.292416
away_odds_match_winner                 3286     4.221046
home_odds_match_winner                 3286     4.221046
home_break_points_saved_perc           1673     2.149060
away_break_points_won_perc             1673     2.149060
home_break_points_won_perc             1601     2.056572
away_break_points_saved_perc           1601     2.056572
away_set_2_score                       1530     1.965368
home_set_2_score                       1530     1.965368
round                                  1263     1.622392
home_service_points_won_perc           1172     1.505498
away_service_points_won_perc           1172     1.505498
home_return_points_won_perc            1172     1.505498
away_return_points_won_perc            1172     1.505498
home_aces                              1167     1.499075
away_aces                              1167     1.499075
home_double_faults                     1167     1.499075
away_double_faults                     1167     1.499075
away_set_1_score                        962     1.235741
home_set_1_score                        962     1.235741
away_set_score                          962     1.235741
home_set_score                          962     1.235741
winner_code                             576     0.739903

## Building Primitive Model

In [16]:
# Create our modeling population
completed_matches = df[
    (df["status"] == "FINISHED") &
    (df["status_extra"] == "FINISHED") &
    (df["winner_code"].notna())
].copy()

In [17]:
completed_matches.size

3417984

In [18]:
completed_matches["home_win"] = (
    completed_matches["winner_code"] == 1
).astype(int)

In [19]:
completed_matches["home_win"].value_counts()

home_win
1    38587
0    35717
Name: count, dtype: int64

## Building baseline

In [20]:
baseline = completed_matches.dropna(
    subset=["home_rank", "away_rank"]
).copy()

In [21]:
baseline.head(10)

,match_id,season_year,tour_type,date_timestamp,tournament,round,surface,status,status_extra,home_name,...,away_double_faults,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win
28,76655088,2021,1,1610009400,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Basilashvili N.,...,1.0,60.0,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1
30,37915000,2021,1,1610013300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Celikbilek A.,...,3.0,69.0,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1
31,59286256,2021,1,1610016300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Ruusuvuori E.,...,0.0,80.0,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1
33,42175550,2021,1,1610017500,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Caruso S.,...,2.0,58.0,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0
34,77512211,2021,1,1610020800,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Herbert P.,...,1.0,51.0,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0
35,30910475,2021,1,1610021700,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Kecmanovic M.,...,3.0,54.0,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0
36,30200362,2021,1,1610036100,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Bellucci T.,...,1.0,54.0,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0
37,37109764,2021,1,1610041200,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Paul T.,...,4.0,66.0,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1
38,36281527,2021,1,1610048400,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Mager G.,...,4.0,67.0,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1
39,24205146,2021,1,1610061000,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Kwon S.,...,1.0,66.0,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0

In [22]:
baseline["predicted_home_win"] = (
    baseline["home_rank"] < baseline["away_rank"]
).astype(int)

In [23]:
baseline.head(10)

,match_id,season_year,tour_type,date_timestamp,tournament,round,surface,status,status_extra,home_name,...,home_service_points_won_perc,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win,predicted_home_win
28,76655088,2021,1,1610009400,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Basilashvili N.,...,60.0,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1,1
30,37915000,2021,1,1610013300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Celikbilek A.,...,69.0,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1,0
31,59286256,2021,1,1610016300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Ruusuvuori E.,...,80.0,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1,0
33,42175550,2021,1,1610017500,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Caruso S.,...,58.0,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0,0
34,77512211,2021,1,1610020800,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Herbert P.,...,51.0,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0,0
35,30910475,2021,1,1610021700,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Kecmanovic M.,...,54.0,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0,1
36,30200362,2021,1,1610036100,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Bellucci T.,...,54.0,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0,0
37,37109764,2021,1,1610041200,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Paul T.,...,66.0,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1,1
38,36281527,2021,1,1610048400,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Mager G.,...,67.0,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1,1
39,24205146,2021,1,1610061000,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Kwon S.,...,66.0,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0,1

In [24]:
from sklearn.metrics import accuracy_score

baseline_accuracy = accuracy_score(
    baseline["home_win"],
    baseline["predicted_home_win"]
)

print(f"The baseline accuracy score is: {baseline_accuracy*100}%")

The baseline accuracy score is: 62.54329539831767%

## Logistic Regression Model V1

In [25]:
model_data = completed_matches.copy()

model_data["rank_diff"] = (
    model_data["away_rank"] - model_data["home_rank"]
)

model_data["points_diff"] = (
    model_data["home_points"] - model_data["away_points"]
)

In [26]:
model_data[
    [
        "home_name",
        "away_name",
        "home_rank",
        "away_rank",
        "rank_diff",
        "home_points",
        "away_points",
        "points_diff",
        "home_win"
    ]
].head(50)

,home_name,away_name,home_rank,away_rank,rank_diff,home_points,away_points,points_diff,home_win
0,Galovic V.,Dougaz A.,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Sakamoto P.,Young D.,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Escobar G.,Quiroz R.,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Barrios Vera T.,Harrison C.,NaN,NaN,NaN,NaN,NaN,NaN,0
6,Oliveira G.,Draxl L.,NaN,NaN,NaN,NaN,NaN,NaN,1
7,Lock B.,King K.,NaN,NaN,NaN,NaN,NaN,NaN,0
8,Kavcic B.,Tokac T.,NaN,NaN,NaN,NaN,NaN,NaN,1
9,Ortega-Olmedo R.,Vavassori A.,NaN,NaN,NaN,NaN,NaN,NaN,0
10,Golubev A.,Molcan A.,NaN,NaN,NaN,NaN,NaN,NaN,0
11,Andreev A.,Klein L.,NaN,NaN,NaN,NaN,NaN,NaN,1
12,Pellegrino A.,Aksu C.,NaN,NaN,NaN,NaN,NaN,NaN,1
13,Sachko V.,Vrbensky M.,NaN,NaN,NaN,NaN,NaN,NaN,0
14,Krstin P.,Turker M. N.,NaN,NaN,NaN,NaN,NaN,NaN,0
15,Bachinger M.,Orlov V.,NaN,NaN,NaN,NaN,NaN,NaN,1
16,Heliovaara H.,Sasikumar M.,NaN,NaN,NaN,NaN,NaN,NaN,1
17,Basic M.,Kuzmanov D.,NaN,NaN,NaN,NaN,NaN,NaN,0
19,Lazarov A.,Miedler L.,NaN,NaN,NaN,NaN,NaN,NaN,0
20,Galovic V.,Quiroz R.,NaN,NaN,NaN,NaN,NaN,NaN,0
21,Young D.,Kozlov S.,NaN,NaN,NaN,NaN,NaN,NaN,1
22,Harrison C.,Khan Z.,NaN,NaN,NaN,NaN,NaN,NaN,1
23,Oliveira G.,King K.,NaN,NaN,NaN,NaN,NaN,NaN,0
24,Kavcic B.,Molcan A.,NaN,NaN,NaN,NaN,NaN,NaN,0
25,Turker M. N.,Vrbensky M.,NaN,NaN,NaN,NaN,NaN,NaN,0
26,Pellegrino A.,Kuzmanov D.,NaN,NaN,NaN,NaN,NaN,NaN,0
27,Vavassori A.,Andreev A.,NaN,NaN,NaN,NaN,NaN,NaN,0
28,Basilashvili N.,Arnaboldi A.,40.0,267.0,227.0,1395.0,206.0,1189.0,1
29,Kotov P.,Heliovaara H.,NaN,NaN,NaN,NaN,NaN,NaN,1
30,Celikbilek A.,Zuk K.,309.0,262.0,-47.0,150.0,209.0,-59.0,1
31,Ruusuvuori E.,Vesely J.,87.0,67.0,-20.0,806.0,928.0,-122.0,1
32,Bachinger M.,Miedler L.,NaN,NaN,NaN,NaN,NaN,NaN,1
33,Caruso S.,Bublik A.,76.0,49.0,-27.0,858.0,1090.0,-232.0,0
34,Herbert P.,Goffin D.,83.0,16.0,-67.0,822.0,2555.0,-1733.0,0
35,Kecmanovic M.,Travaglia S.,42.0,75.0,33.0,1328.0,869.0,459.0,0
36,Bellucci T.,Monteiro T.,281.0,84.0,-197.0,185.0,820.0,-635.0,0
37,Paul T.,Nam Ji S.,52.0,268.0,216.0,1080.0,205.0,875.0,1
38,Mager G.,Harrison R.,101.0,481.0,380.0,733.0,73.0,660.0,1
39,Kwon S.,Korda S.,95.0,119.0,24.0,768.0,566.0,202.0,0
40,McDonald M.,Querrey S.,194.0,56.0,-138.0,335.0,1065.0,-730.0,0
41,Kotov P.,Struff J-L.,269.0,37.0,-232.0,205.0,1450.0,-1245.0,0
42,Lamasine T.,Gerasimov E.,271.0,78.0,-193.0,204.0,840.0,-636.0,1
43,Andreev A.,Ilhan M.,564.0,571.0,7.0,52.0,51.0,1.0,1
44,Molcan A.,Grenier H.,313.0,250.0,-63.0,145.0,220.0,-75.0,0
45,Chardy J.,Albot R.,72.0,85.0,13.0,880.0,817.0,63.0,1
46,Berrettini M.,Kirkin E.,10.0,446.0,436.0,3085.0,83.0,3002.0,1
47,Jaziri M.,De Minaur A.,249.0,23.0,-226.0,220.0,1860.0,-1640.0,0
49,Fognini F.,Vrbensky M.,17.0,311.0,294.0,2400.0,148.0,2252.0,1
51,Etcheverry T. M.,Harrison C.,256.0,789.0,533.0,216.0,22.0,194.0,0
52,Galan D. E.,Martin A.,115.0,100.0,-15.0,606.0,734.0,-128.0,1
53,Rubin N.,Quiroz R.,251.0,293.0,42.0,219.0,171.0,48.0,0
54,Fratangelo B.,King K.,274.0,304.0,30.0,195.0,154.0,41.0,1

In [27]:
model_data[
    ["home_rank", "away_rank", "home_points", "away_points"]
].isna().mean() * 100

home_rank      31.501669
away_rank      31.546081
home_points    31.501669
away_points    31.546081
dtype: float64

In [28]:
v1_data = model_data.dropna(
    subset=[
        "home_rank",
        "away_rank",
        "home_points",
        "away_points"
    ]
).copy()

In [29]:
print("Original completed matches:", len(model_data))
print("V1 usable matches:", len(v1_data))
print(
    "Percentage retained:",
    len(v1_data) / len(model_data) * 100
)

Original completed matches: 74304
V1 usable matches: 50525
Percentage retained: 67.99768518518519

In [30]:
# Splitting the data
train_v1 = v1_data[
    v1_data["season_year"] <= 2024
].copy()

validation_v1 = v1_data[
    v1_data["season_year"] == 2025
].copy()

In [31]:
train_v1.head(10)

,match_id,season_year,tour_type,date_timestamp,tournament,round,surface,status,status_extra,home_name,...,away_service_points_won_perc,home_return_points_won_perc,away_return_points_won_perc,home_break_points_won_perc,away_break_points_won_perc,home_break_points_saved_perc,away_break_points_saved_perc,home_win,rank_diff,points_diff
28,76655088,2021,1,1610009400,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Basilashvili N.,...,54.0,46.0,40.0,35.0,80.0,20.0,65.0,1,227.0,1189.0
30,37915000,2021,1,1610013300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Celikbilek A.,...,65.0,35.0,31.0,29.0,10.0,90.0,71.0,1,-47.0,-59.0
31,59286256,2021,1,1610016300,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Ruusuvuori E.,...,71.0,29.0,20.0,50.0,0.0,0.0,50.0,1,-20.0,-122.0
33,42175550,2021,1,1610017500,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Caruso S.,...,75.0,25.0,42.0,0.0,38.0,63.0,0.0,0,-27.0,-232.0
34,77512211,2021,1,1610020800,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Herbert P.,...,56.0,44.0,49.0,71.0,42.0,58.0,29.0,0,-67.0,-1733.0
35,30910475,2021,1,1610021700,Antalya ATP,1/16-finals,hard,FINISHED,FINISHED,Kecmanovic M.,...,61.0,39.0,46.0,100.0,56.0,44.0,0.0,0,33.0,459.0
36,30200362,2021,1,1610036100,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Bellucci T.,...,66.0,34.0,46.0,11.0,67.0,33.0,89.0,0,-197.0,-635.0
37,37109764,2021,1,1610041200,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Paul T.,...,51.0,49.0,34.0,67.0,33.0,67.0,33.0,1,216.0,875.0
38,36281527,2021,1,1610048400,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Mager G.,...,61.0,39.0,33.0,50.0,8.0,92.0,50.0,1,380.0,660.0
39,24205146,2021,1,1610061000,Delray Beach ATP,1/16-finals,hard,FINISHED,FINISHED,Kwon S.,...,61.0,39.0,34.0,17.0,75.0,25.0,83.0,0,24.0,202.0

In [32]:
# Checking the size of the training and validation data sets
print("Training data: ", len(train_v1))
print("Validation data: ", len(validation_v1))

Training data:  30832
Validation data:  8999

In [33]:
print(train_v1["season_year"].value_counts().sort_index())
print()
print(validation_v1["season_year"].value_counts().sort_index())

season_year
2021    6623
2022    7722
2023    8111
2024    8376
Name: count, dtype: int64

season_year
2025    8999
Name: count, dtype: int64

In [34]:
# Defining the covariates and response
features_v1 = ["rank_diff", "points_diff"]

X_train = train_v1[features_v1]
y_train = train_v1["home_win"]

X_val = validation_v1[features_v1]
y_val = validation_v1["home_win"]

In [35]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train shape: (30832, 2)
y_train shape: (30832,)
X_val shape: (8999, 2)
y_val shape: (8999,)

In [36]:
X_train.head()

    rank_diff  points_diff
28      227.0       1189.0
30      -47.0        -59.0
31      -20.0       -122.0
33      -27.0       -232.0
34      -67.0      -1733.0

In [37]:
# Fitting the logistic model
from sklearn.linear_model import LogisticRegression

log_reg_v1 = LogisticRegression(max_iter=2000)

log_reg_v1.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [38]:
print("Intercept:", log_reg_v1.intercept_[0])

for feature, coefficient in zip(
    features_v1,
    log_reg_v1.coef_[0]
):
    print(feature, ":", coefficient)

Intercept: 6.837326526350055e-07
rank_diff : 0.001971020174479783
points_diff : 0.00032663996633854416

In [39]:
# Predictions made by our model
val_predictions = log_reg_v1.predict(X_val)

In [40]:
# The prediction probabilites
val_probabilities = log_reg_v1.predict_proba(X_val)[:, 1]

In [41]:
print("The value predictions for the first 10 observations: ", val_predictions[:10])
print("The value probabilities for the first 10 observations: ", val_probabilities[:10])

The value predictions for the first 10 observations:  [1 1 1 1 1 1 0 1 1 1]
The value probabilities for the first 10 observations:  [0.59164014 0.57896765 0.80351223 0.60958457 0.70116809 0.78635222
 0.29878953 0.9315902  0.72122947 0.5290016 ]

In [42]:
# Calculating the accuracy score
from sklearn.metrics import accuracy_score

v1_accuracy = accuracy_score(
    y_val,
    val_predictions
)

print("Logistic Regression V1 Accuracy:", round(v1_accuracy*100, 2), "%")

Logistic Regression V1 Accuracy: 62.72 %

In [43]:
from sklearn.metrics import log_loss

v1_log_loss = log_loss(
    y_val,
    val_probabilities
)

print("Logistic Regression V1 Log Loss:", v1_log_loss)

Logistic Regression V1 Log Loss: 0.6466771797539345

## Logistic Regression V2
- This model will use the player's previous performance as the covariates
- The performance in this case would be the average of the ace points, win rates, difference in the games within winning sets, average of points lost due to double faults.

In [44]:
# Creating the history for the home player
home_history = completed_matches[[
    "match_id",
    "date_timestamp",
    "season_year",
    "surface",
    "home_id",
    "home_name",
    "away_id",
    "away_name",
    "winner_code",
    "home_aces",
    "home_double_faults",
    "home_service_points_won_perc",
    "home_return_points_won_perc",
    "home_break_points_won_perc",
    "home_break_points_saved_perc"
]].copy()

In [45]:
home_history = home_history.rename(columns={
    "home_id": "player_id",
    "home_name": "player_name",
    "away_id": "opponent_id",
    "away_name": "opponent_name",
    "home_aces": "aces",
    "home_double_faults": "double_faults",
    "home_service_points_won_perc": "service_points_won_perc",
    "home_return_points_won_perc": "return_points_won_perc",
    "home_break_points_won_perc": "break_points_won_perc",
    "home_break_points_saved_perc": "break_points_saved_perc"
})

In [46]:
home_history["won"] = (
    home_history["winner_code"] == 1
).astype(int)

In [47]:
home_history.head(50)

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4,20264415,1609870500,2021,hard,376007,Barrios Vera T.,884091,Harrison C.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
6,60708459,1609879800,2021,hard,303110,Oliveira G.,806525,Draxl L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
7,16746158,1609887000,2021,hard,132962,Lock B.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
8,92238253,1609923000,2021,hard,276062,Kavcic B.,494292,Tokac T.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
9,89146752,1609923600,2021,hard,287612,Ortega-Olmedo R.,489220,Vavassori A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
10,74669820,1609925400,2021,hard,502076,Golubev A.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
11,71170975,1609927500,2021,hard,598150,Andreev A.,505077,Klein L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
12,30711940,1609927800,2021,hard,273580,Pellegrino A.,996327,Aksu C.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
13,72595040,1609928400,2021,hard,626903,Sachko V.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
14,32846556,1609930800,2021,hard,372643,Krstin P.,426933,Turker M. N.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
15,39551039,1609933800,2021,hard,164915,Bachinger M.,200057,Orlov V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
16,67392456,1609934400,2021,hard,338721,Heliovaara H.,966030,Sasikumar M.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
17,54035930,1609934400,2021,hard,527695,Basic M.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
19,89913477,1609938300,2021,hard,783429,Lazarov A.,810765,Miedler L.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
20,53269779,1609949100,2021,hard,479435,Galovic V.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
21,89813135,1609950000,2021,hard,186820,Young D.,649763,Kozlov S.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
22,42200729,1609955400,2021,hard,884091,Harrison C.,846957,Khan Z.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
23,91215092,1609966200,2021,hard,303110,Oliveira G.,130774,King K.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
24,59537670,1610003100,2021,hard,276062,Kavcic B.,583404,Molcan A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
25,55206216,1610003400,2021,hard,426933,Turker M. N.,191513,Vrbensky M.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
26,63761082,1610003400,2021,hard,273580,Pellegrino A.,237834,Kuzmanov D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
27,80589723,1610004000,2021,hard,489220,Vavassori A.,598150,Andreev A.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
28,76655088,1610009400,2021,hard,309924,Basilashvili N.,659274,Arnaboldi A.,1.0,3.0,4.0,60.0,46.0,35.0,20.0,1
29,36126999,1610011500,2021,hard,627199,Kotov P.,338721,Heliovaara H.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
30,37915000,1610013300,2021,hard,368199,Celikbilek A.,822730,Zuk K.,1.0,4.0,4.0,69.0,35.0,29.0,90.0,1
31,59286256,1610016300,2021,hard,384119,Ruusuvuori E.,191042,Vesely J.,1.0,1.0,0.0,80.0,29.0,50.0,0.0,1
32,64520760,1610016600,2021,hard,164915,Bachinger M.,810765,Miedler L.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
33,42175550,1610017500,2021,hard,474240,Caruso S.,732840,Bublik A.,2.0,0.0,3.0,58.0,25.0,0.0,63.0,0
34,77512211,1610020800,2021,hard,321867,Herbert P.,811823,Goffin D.,2.0,7.0,4.0,51.0,44.0,71.0,58.0,0
35,30910475,1610021700,2021,hard,692911,Kecmanovic M.,944674,Travaglia S.,2.0,3.0,2.0,54.0,39.0,100.0,44.0,0
36,30200362,1610036100,2021,hard,632715,Bellucci T.,261646,Monteiro T.,2.0,3.0,3.0,54.0,34.0,11.0,33.0,0
37,37109764,1610041200,2021,hard,650985,Paul T.,315309,Nam Ji S.,1.0,5.0,0.0,66.0,49.0,67.0,67.0,1
38,36281527,1610048400,2021,hard,528890,Mager G.,239088,Harrison R.,1.0,9.0,3.0,67.0,39.0,50.0,92.0,1
39,24205146,1610061000,2021,hard,614106,Kwon S.,261903,Korda S.,2.0,4.0,4.0,66.0,39.0,17.0,25.0,0
40,61718845,1610068200,2021,hard,476352,McDonald M.,110329,Querrey S.,2.0,4.0,2.0,60.0,33.0,14.0,50.0,0
41,44560846,1610089800,2021,hard,627199,Kotov P.,855008,Struff J-L.,2.0,2.0,1.0,51.0,41.0,29.0,58.0,0
42,82040147,1610089800,2021,hard,981822,Lamasine T.,431960,Gerasimov E.,1.0,0.0,1.0,62.0,45.0,100.0,50.0,1
43,77654561,1610090100,2021,hard,598150,Andreev A.,791393,Ilhan M.,1.0,0.0,0.0,67.0,45.0,67.0,50.0,1
44,96620860,1610091300,2021,hard,583404,Molcan A.,947022,Grenier H.,2.0,3.0,2.0,58.0,35.0,29.0,56.0,0
45,58255115,1610095800,2021,hard,311520,Chardy J.,281568,Albot R.,1.0,5.0,4.0,66.0,52.0,45.0,0.0,1
46,19523148,1610095800,2021,hard,692847,Berrettini M.,117175,Kirkin E.,1.0,8.0,2.0,82.0,51.0,80.0,0.0,1
47,24498577,1610096100,2021,hard,402865,Jaziri M.,284548,De Minaur A.,2.0,3.0,4.0,41.0,19.0,0.0,50.0,0
49,18933339,1610100300,2021,hard,474237,Fognini F.,191513,Vrbensky M.,1.0,0.0,4.0,65.0,44.0,30.0,0.0,1
51,21596449,1610121900,2021,hard,418622,Etcheverry T. M.,884091,Harrison C.,2.0,4.0,3.0,51.0,29.0,33.0,69.0,0
52,46017359,1610127600,2021,hard,613323,Galan D. E.,632445,Martin A.,1.0,3.0,2.0,67.0,44.0,43.0,83.0,1
53,22539845,1610128500,2021,hard,429215,Rubin N.,338092,Quiroz R.,2.0,5.0,6.0,53.0,38.0,75.0,29.0,0
54,50355974,1610133300,2021,hard,849776,Fratangelo B.,130774,King K.,1.0,0.0,0.0,73.0,51.0,67.0,100.0,1

In [48]:
away_history = completed_matches[[
    "match_id",
    "date_timestamp",
    "season_year",
    "surface",
    "away_id",
    "away_name",
    "home_id",
    "home_name",
    "winner_code",
    "away_aces",
    "away_double_faults",
    "away_service_points_won_perc",
    "away_return_points_won_perc",
    "away_break_points_won_perc",
    "away_break_points_saved_perc"
]].copy()

In [49]:
away_history = away_history.rename(columns={
    "away_id": "player_id",
    "away_name": "player_name",
    "home_id": "opponent_id",
    "home_name": "opponent_name",
    "away_aces": "aces",
    "away_double_faults": "double_faults",
    "away_service_points_won_perc": "service_points_won_perc",
    "away_return_points_won_perc": "return_points_won_perc",
    "away_break_points_won_perc": "break_points_won_perc",
    "away_break_points_saved_perc": "break_points_saved_perc"
})

In [50]:
away_history["won"] = (
    away_history["winner_code"] == 2
).astype(int)

In [51]:
away_history[[
    "match_id",
    "player_name",
    "opponent_name",
    "won"
]].head()

   match_id  player_name    opponent_name  won
0  50962420    Dougaz A.       Galovic V.    0
2  41905728     Young D.      Sakamoto P.    1
3  31331956    Quiroz R.       Escobar G.    1
4  20264415  Harrison C.  Barrios Vera T.    1
6  60708459     Draxl L.      Oliveira G.    0

In [52]:
player_history = pd.concat(
    [home_history, away_history],
    ignore_index=True
)

player_history = player_history.sort_values(
    ["date_timestamp", "match_id"]
).reset_index(drop=True)

In [53]:
player_history.shape

(148608, 16)

In [54]:
player_history.head()

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
1,50962420,1609859400,2021,hard,283198,Dougaz A.,479435,Galovic V.,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,41905728,1609862100,2021,hard,186820,Young D.,839524,Sakamoto P.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0

In [55]:
# Rolling feature: Win rate of the last 10 matches
player_history["win_rate_last_10"] = (
    player_history
    .groupby("player_id")["won"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [56]:
player_history[
    ["player_name", "date_timestamp", "won", "win_rate_last_10"]
].tail(50)

             player_name  date_timestamp  won  win_rate_last_10
148558      Mashtakov N.      1788174000    1          0.400000
148559          Opitz J.      1788174000    0          0.500000
148560          Ayeni A.      1788175200    0          0.300000
148561          Cacao T.      1788175200    1          0.200000
148562        Potenza L.      1788175800    1          0.400000
148563          Masur D.      1788175800    0          0.400000
148564            Cui J.      1788175800    0          0.600000
148565     Trotter J. K.      1788175800    1          0.600000
148566    Overbeck C. E.      1788176400    1          0.500000
148567       Peniston R.      1788176400    0          0.300000
148568         Schoen P.      1788176400    1          0.500000
148569          Fuele M.      1788176400    0          0.600000
148570        Piraino G.      1788176400    0          0.600000
148571      Obradovic D.      1788176400    1          0.100000
148572      Agamenone F.      1788178200    0          0.300000
148573         Giunta M.      1788178200    1          0.300000
148574          Dodig M.      1788178500    1          0.600000
148575       Poljicak M.      1788178500    0          0.700000
148576           Gray A.      1788179400    0          0.400000
148577          Jones M.      1788179400    1          0.400000
148578          Heide G.      1788182100    1          0.400000
148579        Marques G.      1788182100    0          0.000000
148580          Kolar Z.      1788183000    0          0.200000
148581   Roca Batalla O.      1788183000    1          0.400000
148582          Bueno G.      1788183300    1          0.600000
148583  Reis Da Silva J.      1788183300    0          0.300000
148584   Guillen Meza A.      1788185100    0          0.100000
148585     Schoenhaus M.      1788185100    1          0.300000
148586        Lazarov G.      1788186300    0          0.666667
148587          Milic O.      1788186300    1          0.400000
148588       Monteiro T.      1788187800    1          0.700000
148589      Coppejans K.      1788187800    0          0.500000
148590       Petkovic M.      1788188400    1          0.400000
148591         Torres T.      1788188400    0          0.600000
148592       Vacherot V.      1788188700    1          0.400000
148593      Kovacevic A.      1788188700    0          0.400000
148594       Virtanen O.      1788189000    0          0.600000
148595         Rublev A.      1788189000    1          0.600000
148596    Varillas J. P.      1788189000    1          0.600000
148597        Kumstat J.      1788189000    0          1.000000
148598      Tsitsipas S.      1788189000    1          0.600000
148599           Fils A.      1788189000    0          0.900000
148600     Tirante T. A.      1788195300    0          0.800000
148601      Mannarino A.      1788195300    1          0.300000
148602         Gorzny S.      1788196800    1          0.500000
148603      Collignon R.      1788196800    0          0.400000
148604      Michelsen A.      1788199200    1          0.700000
148605           Cina F.      1788199200    0          0.600000
148606          Vukic A.      1788203100    0          0.600000
148607       Sakamoto R.      1788203100    1          0.700000

In [57]:
# Rolling feature: Average number of aces of the last 10 matches
player_history["avg_aces_last_10"] = (
    player_history
    .groupby("player_id")["aces"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [58]:
player_history.tail(50)

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,double_faults,service_points_won_perc,return_points_won_perc,break_points_won_perc,break_points_saved_perc,won,win_rate_last_10,avg_aces_last_10
148558,49892263,1788174000,2026,clay,889638,Mashtakov N.,113609,Opitz J.,1.0,1.0,1.0,68.0,40.0,100.000000,100.000000,1,0.400000,1.600000
148559,49892263,1788174000,2026,clay,113609,Opitz J.,889638,Mashtakov N.,1.0,5.0,2.0,60.0,32.0,0.000000,0.000000,0,0.500000,6.100000
148560,52532372,1788175200,2026,clay,154108,Ayeni A.,800812,Cacao T.,2.0,2.0,6.0,53.0,38.0,40.000000,0.000000,0,0.300000,5.100000
148561,52532372,1788175200,2026,clay,800812,Cacao T.,154108,Ayeni A.,2.0,6.0,0.0,62.0,47.0,100.000000,60.000000,1,0.200000,2.100000
148562,36323795,1788175800,2026,hard,406901,Potenza L.,470661,Masur D.,1.0,5.0,6.0,57.0,42.0,50.000000,40.000000,1,0.400000,1.600000
148563,36323795,1788175800,2026,hard,470661,Masur D.,406901,Potenza L.,1.0,8.0,3.0,58.0,43.0,60.000000,50.000000,0,0.400000,4.600000
148564,67893108,1788175800,2026,hard,747544,Cui J.,557178,Trotter J. K.,2.0,3.0,2.0,65.0,18.0,NaN,33.333333,0,0.600000,4.000000
148565,67893108,1788175800,2026,hard,557178,Trotter J. K.,747544,Cui J.,2.0,10.0,1.0,82.0,35.0,66.666667,NaN,1,0.600000,3.200000
148566,17059978,1788176400,2026,hard,653025,Overbeck C. E.,362646,Peniston R.,1.0,1.0,4.0,59.0,54.0,41.666667,71.428571,1,0.500000,5.600000
148567,17059978,1788176400,2026,hard,362646,Peniston R.,653025,Overbeck C. E.,1.0,0.0,12.0,46.0,41.0,28.571429,58.333333,0,0.300000,1.900000
148568,17913922,1788176400,2026,clay,505083,Schoen P.,211205,Fuele M.,1.0,3.0,0.0,59.0,42.0,33.333333,63.636364,1,0.500000,6.500000
148569,17913922,1788176400,2026,clay,211205,Fuele M.,505083,Schoen P.,1.0,1.0,3.0,58.0,41.0,36.363636,66.666667,0,0.600000,2.700000
148570,51836658,1788176400,2026,clay,462888,Piraino G.,980740,Obradovic D.,2.0,4.0,9.0,56.0,39.0,71.428571,50.000000,0,0.600000,2.000000
148571,51836658,1788176400,2026,clay,980740,Obradovic D.,462888,Piraino G.,2.0,2.0,2.0,61.0,44.0,50.000000,28.571429,1,0.100000,1.300000
148572,28924564,1788178200,2026,clay,680600,Agamenone F.,948801,Giunta M.,2.0,1.0,4.0,57.0,33.0,100.000000,40.000000,0,0.300000,2.700000
148573,28924564,1788178200,2026,clay,948801,Giunta M.,680600,Agamenone F.,2.0,1.0,1.0,67.0,43.0,60.000000,0.000000,1,0.300000,7.100000
148574,95651770,1788178500,2026,clay,536921,Dodig M.,713575,Poljicak M.,1.0,7.0,0.0,82.0,43.0,75.000000,NaN,1,0.600000,6.400000
148575,95651770,1788178500,2026,clay,713575,Poljicak M.,536921,Dodig M.,1.0,2.0,1.0,57.0,18.0,NaN,25.000000,0,0.700000,7.800000
148576,69698781,1788179400,2026,hard,859641,Gray A.,251433,Jones M.,2.0,3.0,7.0,55.0,34.0,33.333333,33.333333,0,0.400000,4.800000
148577,69698781,1788179400,2026,hard,251433,Jones M.,859641,Gray A.,2.0,4.0,1.0,66.0,45.0,66.666667,66.666667,1,0.400000,7.000000
148578,84423979,1788182100,2026,clay,312908,Heide G.,592845,Marques G.,1.0,3.0,1.0,77.0,40.0,60.000000,100.000000,1,0.400000,2.500000
148579,84423979,1788182100,2026,clay,592845,Marques G.,312908,Heide G.,1.0,4.0,3.0,60.0,23.0,0.000000,40.000000,0,0.000000,2.000000
148580,15370496,1788183000,2026,clay,255826,Kolar Z.,198966,Roca Batalla O.,2.0,1.0,1.0,34.0,36.0,33.333333,14.285714,0,0.200000,1.800000
148581,15370496,1788183000,2026,clay,198966,Roca Batalla O.,255826,Kolar Z.,2.0,1.0,1.0,64.0,66.0,85.714286,66.666667,1,0.400000,3.700000
148582,97760508,1788183300,2026,clay,924945,Bueno G.,835430,Reis Da Silva J.,1.0,1.0,1.0,65.0,45.0,25.000000,66.666667,1,0.600000,0.500000
148583,97760508,1788183300,2026,clay,835430,Reis Da Silva J.,924945,Bueno G.,1.0,2.0,0.0,55.0,35.0,33.333333,75.000000,0,0.300000,3.600000
148584,87993057,1788185100,2026,clay,272711,Guillen Meza A.,843952,Schoenhaus M.,2.0,2.0,4.0,54.0,32.0,14.285714,64.285714,0,0.100000,3.200000
148585,87993057,1788185100,2026,clay,843952,Schoenhaus M.,272711,Guillen Meza A.,2.0,9.0,1.0,68.0,46.0,35.714286,85.714286,1,0.300000,5.000000
148586,18150239,1788186300,2026,clay,956932,Lazarov G.,127476,Milic O.,2.0,1.0,4.0,55.0,45.0,71.428571,41.666667,0,0.666667,0.833333
148587,18150239,1788186300,2026,clay,127476,Milic O.,956932,Lazarov G.,2.0,3.0,7.0,55.0,45.0,58.333333,28.571429,1,0.400000,2.400000
148588,17197688,1788187800,2026,clay,261646,Monteiro T.,786070,Coppejans K.,1.0,2.0,3.0,74.0,43.0,80.000000,50.000000,1,0.700000,4.800000
148589,17197688,1788187800,2026,clay,786070,Coppejans K.,261646,Monteiro T.,1.0,2.0,4.0,57.0,26.0,50.000000,20.000000,0,0.500000,2.000000
148590,50902374,1788188400,2026,clay,245726,Petkovic M.,347693,Torres T.,1.0,2.0,4.0,61.0,43.0,54.545455,37.500000,1,0.400000,1.400000
148591,50902374,1788188400,2026,clay,347693,Torres T.,245726,Petkovic M.,1.0,1.0,3.0,57.0,39.0,62.500000,45.454545,0,0.600000,4.200000
148592,91573004,1788188700,2026,hard,331620,Vacherot V.,655170,Kovacevic A.,1.0,14.0,3.0,79.0,40.0,36.363636,NaN,1,0.400000,8.300000
148593,91573004,1788188700,2026,hard,655170,Kovacevic A.,331620,Vacherot V.,1.0,8.0,6.0,60.0,21.0,NaN,63.636364,0,0.400000,9.000000
148594,30302000,1788189000,2026,hard,923060,Virtanen O.,433587,Rublev A.,2.0,19.0,7.0,59.0,26.0,25.000000,70.833333,0,0.600000,8.600000
148595,30302000,1788189000,2026,hard,433587,Rublev A.,923060,Virtanen O.,2.0,20.0,3.0,74.0,41.0,29.166667,75.000000,1,0.600000,9.700000
148596,76116393,1788189000,2026,clay,820964,Varillas J. P.,363629,Kumstat J.,1.0,3.0,0.0,77.0,39.0,40.000000,100.000000,1,0.600000,5.000000
148597,76116393,1788189000,2026,clay,363629,Kumstat J.,820964,Varillas J. P.,1.0,4.0,3.0,61.0,23.0,0.000000,60.000000,0,1.000000,8.400000
148598,89567411,1788189000,2026,hard,249143,Tsitsipas S.,342082,Fils A.,1.0,14.0,7.0,64.0,38.0,41.666667,62.500000,1,0.600000,6.800000
148599,89567411,1788189000,2026,hard,342082,Fils A.,249143,Tsitsipas S.,1.0,10.0,4.0,62.0,36.0,37.500000,58.333333,0,0.900000,6.400000
148600,95629557,1788195300,2026,hard,799088,Tirante T. A.,136276,Mannarino A.,2.0,19.0,16.0,60.0,36.0,40.000000,50.000000,0,0.800000,8.900000
148601,95629557,1788195300,2026,hard,136276,Mannarino A.,799088,Tirante T. A.,2.0,4.0,1.0,64.0,40.0,50.000000,60.000000,1,0.300000,2.600000
148602,14929371,1788196800,2026,hard,787151,Gorzny S.,273841,Collignon R.,1.0,12.0,6.0,60.0,38.0,38.461538,77.272727,1,0.500000,6.900000
148603,14929371,1788196800,2026,hard,273841,Collignon R.,787151,Gorzny S.,1.0,13.0,17.0,62.0,40.0,22.727273,61.538462,0,0.400000,7.600000
148604,96460674,1788199200,2026,hard,207923,Michelsen A.,639555,Cina F.,1.0,6.0,8.0,66.0,51.0,40.000000,100.000000,1,0.700000,6.200000
148605,96460674,1788199200,2026,hard,639555,Cina F.,207923,Michelsen A.,1.0,2.0,1.0,49.0,34.0,0.000000,60.000000,0,0.600000,6.500000
148606,55918190,1788203100,2026,hard,444516,Vukic A.,852781,Sakamoto R.,2.0,22.0,5.0,69.0,28.0,100.000000,62.500000,0,0.600000,8.900000
148607,55918190,1788203100,2026,hard,852781,Sakamoto R.,444516,Vukic A.,2.0,38.0,3.0,72.0,31.0,37.500000,0.000000,1,0.700000,9.800000

In [59]:
# Rolling feature: Average number of double faults in the last 10 matches
player_history["avg_double_faults_last_10"] = (
    player_history
    .groupby("player_id")["double_faults"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [60]:
player_history[["player_name", "won", "win_rate_last_10", "avg_aces_last_10","avg_double_faults_last_10"]].tail(20)

,player_name,won,win_rate_last_10,avg_aces_last_10,avg_double_faults_last_10
148588,Monteiro T.,1,0.7,4.8,2.4
148589,Coppejans K.,0,0.5,2.0,2.0
148590,Petkovic M.,1,0.4,1.4,3.6
148591,Torres T.,0,0.6,4.2,5.5
148592,Vacherot V.,1,0.4,8.3,3.7
148593,Kovacevic A.,0,0.4,9.0,5.1
148594,Virtanen O.,0,0.6,8.6,4.9
148595,Rublev A.,1,0.6,9.7,3.3
148596,Varillas J. P.,1,0.6,5.0,2.0
148597,Kumstat J.,0,1.0,8.4,2.3
148598,Tsitsipas S.,1,0.6,6.8,3.2
148599,Fils A.,0,0.9,6.4,2.2
148600,Tirante T. A.,0,0.8,8.9,3.2
148601,Mannarino A.,1,0.3,2.6,3.0
148602,Gorzny S.,1,0.5,6.9,4.8
148603,Collignon R.,0,0.4,7.6,5.7
148604,Michelsen A.,1,0.7,6.2,3.8
148605,Cina F.,0,0.6,6.5,4.2
148606,Vukic A.,0,0.6,8.9,1.2
148607,Sakamoto R.,1,0.7,9.8,3.1

In [61]:
# Rolling feature: Average service points won % in the last 10 matches
player_history["avg_service_points_won_last_10"] = (
    player_history
    .groupby("player_id")["service_points_won_perc"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [62]:
player_history[["player_name", "won", "win_rate_last_10", "avg_aces_last_10","avg_double_faults_last_10", "avg_service_points_won_last_10"]].tail(20)

,player_name,won,win_rate_last_10,avg_aces_last_10,avg_double_faults_last_10,avg_service_points_won_last_10
148588,Monteiro T.,1,0.7,4.8,2.4,66.4
148589,Coppejans K.,0,0.5,2.0,2.0,59.7
148590,Petkovic M.,1,0.4,1.4,3.6,60.9
148591,Torres T.,0,0.6,4.2,5.5,56.7
148592,Vacherot V.,1,0.4,8.3,3.7,65.1
148593,Kovacevic A.,0,0.4,9.0,5.1,64.8
148594,Virtanen O.,0,0.6,8.6,4.9,65.9
148595,Rublev A.,1,0.6,9.7,3.3,68.9
148596,Varillas J. P.,1,0.6,5.0,2.0,61.5
148597,Kumstat J.,0,1.0,8.4,2.3,71.5
148598,Tsitsipas S.,1,0.6,6.8,3.2,65.4
148599,Fils A.,0,0.9,6.4,2.2,70.6
148600,Tirante T. A.,0,0.8,8.9,3.2,67.8
148601,Mannarino A.,1,0.3,2.6,3.0,62.4
148602,Gorzny S.,1,0.5,6.9,4.8,62.7
148603,Collignon R.,0,0.4,7.6,5.7,62.2
148604,Michelsen A.,1,0.7,6.2,3.8,66.0
148605,Cina F.,0,0.6,6.5,4.2,65.0
148606,Vukic A.,0,0.6,8.9,1.2,71.7
148607,Sakamoto R.,1,0.7,9.8,3.1,66.6

In [63]:
# Rolling feature: Average return points won % over the last 10 matches
player_history["avg_return_points_won_last_10"] = (
    player_history
    .groupby("player_id")["return_points_won_perc"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [64]:
player_history[["player_name", "won", "win_rate_last_10", "avg_aces_last_10","avg_double_faults_last_10",
                 "avg_service_points_won_last_10", "avg_return_points_won_last_10"]].tail(20)

,player_name,won,win_rate_last_10,avg_aces_last_10,avg_double_faults_last_10,avg_service_points_won_last_10,avg_return_points_won_last_10
148588,Monteiro T.,1,0.7,4.8,2.4,66.4,41.4
148589,Coppejans K.,0,0.5,2.0,2.0,59.7,41.5
148590,Petkovic M.,1,0.4,1.4,3.6,60.9,38.2
148591,Torres T.,0,0.6,4.2,5.5,56.7,43.1
148592,Vacherot V.,1,0.4,8.3,3.7,65.1,33.1
148593,Kovacevic A.,0,0.4,9.0,5.1,64.8,30.8
148594,Virtanen O.,0,0.6,8.6,4.9,65.9,38.6
148595,Rublev A.,1,0.6,9.7,3.3,68.9,38.9
148596,Varillas J. P.,1,0.6,5.0,2.0,61.5,37.9
148597,Kumstat J.,0,1.0,8.4,2.3,71.5,41.6
148598,Tsitsipas S.,1,0.6,6.8,3.2,65.4,35.4
148599,Fils A.,0,0.9,6.4,2.2,70.6,41.5
148600,Tirante T. A.,0,0.8,8.9,3.2,67.8,35.8
148601,Mannarino A.,1,0.3,2.6,3.0,62.4,37.8
148602,Gorzny S.,1,0.5,6.9,4.8,62.7,36.1
148603,Collignon R.,0,0.4,7.6,5.7,62.2,31.6
148604,Michelsen A.,1,0.7,6.2,3.8,66.0,38.0
148605,Cina F.,0,0.6,6.5,4.2,65.0,40.5
148606,Vukic A.,0,0.6,8.9,1.2,71.7,40.1
148607,Sakamoto R.,1,0.7,9.8,3.1,66.6,40.6

In [67]:
# Rolling feature: Average break points won %
player_history["avg_break_points_won_last_10"] = (
    round(player_history
    .groupby("player_id")["break_points_won_perc"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    ),2)
)

In [68]:
player_history[["player_name", "won", "win_rate_last_10", "avg_aces_last_10","avg_double_faults_last_10",
                 "avg_service_points_won_last_10", "avg_return_points_won_last_10", "avg_break_points_won_last_10"]].tail(20)

,player_name,won,win_rate_last_10,avg_aces_last_10,avg_double_faults_last_10,avg_service_points_won_last_10,avg_return_points_won_last_10,avg_break_points_won_last_10
148588,Monteiro T.,1,0.7,4.8,2.4,66.4,41.4,46.07
148589,Coppejans K.,0,0.5,2.0,2.0,59.7,41.5,39.32
148590,Petkovic M.,1,0.4,1.4,3.6,60.9,38.2,53.11
148591,Torres T.,0,0.6,4.2,5.5,56.7,43.1,53.77
148592,Vacherot V.,1,0.4,8.3,3.7,65.1,33.1,40.38
148593,Kovacevic A.,0,0.4,9.0,5.1,64.8,30.8,49.07
148594,Virtanen O.,0,0.6,8.6,4.9,65.9,38.6,45.31
148595,Rublev A.,1,0.6,9.7,3.3,68.9,38.9,39.15
148596,Varillas J. P.,1,0.6,5.0,2.0,61.5,37.9,44.54
148597,Kumstat J.,0,1.0,8.4,2.3,71.5,41.6,43.22
148598,Tsitsipas S.,1,0.6,6.8,3.2,65.4,35.4,33.88
148599,Fils A.,0,0.9,6.4,2.2,70.6,41.5,49.87
148600,Tirante T. A.,0,0.8,8.9,3.2,67.8,35.8,36.83
148601,Mannarino A.,1,0.3,2.6,3.0,62.4,37.8,47.54
148602,Gorzny S.,1,0.5,6.9,4.8,62.7,36.1,49.98
148603,Collignon R.,0,0.4,7.6,5.7,62.2,31.6,34.56
148604,Michelsen A.,1,0.7,6.2,3.8,66.0,38.0,48.05
148605,Cina F.,0,0.6,6.5,4.2,65.0,40.5,40.37
148606,Vukic A.,0,0.6,8.9,1.2,71.7,40.1,35.15
148607,Sakamoto R.,1,0.7,9.8,3.1,66.6,40.6,42.01

In [69]:
# Rolling feature: Average Break Points saved%
player_history["avg_break_points_saved_last_10"] = (
    player_history
    .groupby("player_id")["break_points_saved_perc"]
    .transform(
        lambda s: s.shift(1).rolling(10, min_periods=1).mean()
    )
)

In [70]:
# Feature: Sets won by home and away players individually
set_numbers = [1, 2, 3, 4, 5]

# Calculate sets won by home player
completed_matches["home_sets_won_calc"] = 0

for i in set_numbers:
    home_col = f"home_set_{i}_score"
    away_col = f"away_set_{i}_score"

    completed_matches["home_sets_won_calc"] += (
        completed_matches[home_col] > completed_matches[away_col]
    ).astype(int)

# Calculate sets won by away player
completed_matches["away_sets_won_calc"] = 0

for i in set_numbers:
    home_col = f"home_set_{i}_score"
    away_col = f"away_set_{i}_score"

    completed_matches["away_sets_won_calc"] += (
        completed_matches[away_col] > completed_matches[home_col]
    ).astype(int)

In [73]:
completed_matches[[
    "home_name",
    "away_name",
    "home_set_1_score",
    "away_set_1_score",
    "home_set_2_score",
    "away_set_2_score",
    "home_set_3_score",
    "away_set_3_score",
    "home_sets_won_calc",
    "away_sets_won_calc"
]].head(10)

,home_name,away_name,home_set_1_score,away_set_1_score,home_set_2_score,away_set_2_score,home_set_3_score,away_set_3_score,home_sets_won_calc,away_sets_won_calc
0,Galovic V.,Dougaz A.,6.0,4.0,6.0,3.0,NaN,NaN,2,0
2,Sakamoto P.,Young D.,6.0,3.0,4.0,6.0,2.0,6.0,1,2
3,Escobar G.,Quiroz R.,4.0,6.0,7.0,6.0,5.0,7.0,1,2
4,Barrios Vera T.,Harrison C.,4.0,6.0,4.0,6.0,NaN,NaN,0,2
6,Oliveira G.,Draxl L.,3.0,6.0,6.0,3.0,6.0,2.0,2,1
7,Lock B.,King K.,2.0,6.0,3.0,6.0,NaN,NaN,0,2
8,Kavcic B.,Tokac T.,6.0,2.0,6.0,2.0,NaN,NaN,2,0
9,Ortega-Olmedo R.,Vavassori A.,5.0,7.0,1.0,6.0,NaN,NaN,0,2
10,Golubev A.,Molcan A.,2.0,6.0,5.0,7.0,NaN,NaN,0,2
11,Andreev A.,Klein L.,6.0,3.0,7.0,6.0,NaN,NaN,2,0

In [74]:
# Feature: Total games won by each player in each match
completed_matches["home_games_won"] = 0
completed_matches["away_games_won"] = 0

for i in set_numbers:
    home_col = f"home_set_{i}_score"
    away_col = f"away_set_{i}_score"

    completed_matches["home_games_won"] += (
        completed_matches[home_col].fillna(0)
    )

    completed_matches["away_games_won"] += (
        completed_matches[away_col].fillna(0)
    )

In [75]:
completed_matches["home_game_diff"] = (
    completed_matches["home_games_won"]
    - completed_matches["away_games_won"]
)

completed_matches["away_game_diff"] = (
    completed_matches["away_games_won"]
    - completed_matches["home_games_won"]
)

In [78]:
completed_matches["total_games"] = (
    completed_matches["home_games_won"]
    + completed_matches["away_games_won"]
)

completed_matches["home_games_won_pct"] = (
    round((completed_matches["home_games_won"]
    / completed_matches["total_games"])*100, 2)
)

completed_matches["away_games_won_pct"] = (
    round((completed_matches["away_games_won"]
    / completed_matches["total_games"])*100, 2)
)

In [79]:
completed_matches[[
    "home_name",
    "away_name",
    "home_games_won",
    "away_games_won",
    "home_game_diff",
    "home_games_won_pct",
    "away_games_won_pct"
]].head(10)

,home_name,away_name,home_games_won,away_games_won,home_game_diff,home_games_won_pct,away_games_won_pct
0,Galovic V.,Dougaz A.,12.0,7.0,5.0,63.16,36.84
2,Sakamoto P.,Young D.,12.0,15.0,-3.0,44.44,55.56
3,Escobar G.,Quiroz R.,16.0,19.0,-3.0,45.71,54.29
4,Barrios Vera T.,Harrison C.,8.0,12.0,-4.0,40.00,60.00
6,Oliveira G.,Draxl L.,15.0,11.0,4.0,57.69,42.31
7,Lock B.,King K.,5.0,12.0,-7.0,29.41,70.59
8,Kavcic B.,Tokac T.,12.0,4.0,8.0,75.00,25.00
9,Ortega-Olmedo R.,Vavassori A.,6.0,13.0,-7.0,31.58,68.42
10,Golubev A.,Molcan A.,7.0,13.0,-6.0,35.00,65.00
11,Andreev A.,Klein L.,13.0,9.0,4.0,59.09,40.91

In [80]:
completed_matches["total_sets_played"] = (
    completed_matches["home_sets_won_calc"]
    + completed_matches["away_sets_won_calc"]
)

In [81]:
home_score_stats = completed_matches[[
    "match_id",
    "home_sets_won_calc",
    "total_sets_played",
    "home_games_won_pct",
    "home_game_diff"
]].copy()

home_score_stats = home_score_stats.rename(columns={
    "home_sets_won_calc": "sets_won",
    "home_games_won_pct": "games_won_pct",
    "home_game_diff": "game_diff"
})

home_history = home_history.merge(
    home_score_stats,
    on="match_id",
    how="left"
)

In [82]:
home_history[[
    "player_name",
    "sets_won",
    "total_sets_played",
    "games_won_pct",
    "game_diff"
]].head(10)

        player_name  sets_won  total_sets_played  games_won_pct  game_diff
0        Galovic V.         2                  2          63.16        5.0
1       Sakamoto P.         1                  3          44.44       -3.0
2        Escobar G.         1                  3          45.71       -3.0
3   Barrios Vera T.         0                  2          40.00       -4.0
4       Oliveira G.         2                  3          57.69        4.0
5           Lock B.         0                  2          29.41       -7.0
6         Kavcic B.         2                  2          75.00        8.0
7  Ortega-Olmedo R.         0                  2          31.58       -7.0
8        Golubev A.         0                  2          35.00       -6.0
9        Andreev A.         2                  2          59.09        4.0

In [83]:
away_score_stats = completed_matches[[
    "match_id",
    "away_sets_won_calc",
    "total_sets_played",
    "away_games_won_pct",
    "away_game_diff"
]].copy()

away_score_stats = away_score_stats.rename(columns={
    "away_sets_won_calc": "sets_won",
    "away_games_won_pct": "games_won_pct",
    "away_game_diff": "game_diff"
})

away_history = away_history.merge(
    away_score_stats,
    on="match_id",
    how="left"
)

In [84]:
away_history[[
    "player_name",
    "sets_won",
    "total_sets_played",
    "games_won_pct",
    "game_diff"
]].head(10)

    player_name  sets_won  total_sets_played  games_won_pct  game_diff
0     Dougaz A.         0                  2          36.84       -5.0
1      Young D.         2                  3          55.56        3.0
2     Quiroz R.         2                  3          54.29        3.0
3   Harrison C.         2                  2          60.00        4.0
4      Draxl L.         1                  3          42.31       -4.0
5       King K.         2                  2          70.59        7.0
6      Tokac T.         0                  2          25.00       -8.0
7  Vavassori A.         2                  2          68.42        7.0
8     Molcan A.         2                  2          65.00        6.0
9      Klein L.         0                  2          40.91       -4.0

In [85]:
# Concatinating the two histories
player_history = pd.concat(
    [home_history, away_history],
    ignore_index=True
)

player_history = player_history.sort_values(
    ["date_timestamp", "match_id"]
).reset_index(drop=True)

In [86]:
player_history["sets_won_pct_last_10"] = (
    player_history
    .groupby("player_id")
    .apply(
        lambda g: (
            g["sets_won"].shift(1).rolling(10, min_periods=1).sum()
            /
            g["total_sets_played"].shift(1).rolling(10, min_periods=1).sum()
        )
    )
    .reset_index(level=0, drop=True)
)

/var/folders/7t/s00qhkf90sdgwcv66lcjh2x40000gn/T/ipykernel_18511/4084173964.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

In [87]:
player_history[[
    "player_name",
    "sets_won",
    "total_sets_played",
    "sets_won_pct_last_10"
]].tail(20)

           player_name  sets_won  total_sets_played  sets_won_pct_last_10
148588     Monteiro T.         2                  2              0.652174
148589    Coppejans K.         0                  2              0.500000
148590     Petkovic M.         2                  3              0.454545
148591       Torres T.         1                  3              0.538462
148592     Vacherot V.         3                  3              0.428571
148593    Kovacevic A.         0                  3              0.440000
148594     Virtanen O.         2                  5              0.590909
148595       Rublev A.         3                  5              0.592593
148596  Varillas J. P.         2                  2              0.560000
148597      Kumstat J.         0                  2              0.800000
148598    Tsitsipas S.         3                  4              0.565217
148599         Fils A.         1                  4              0.782609
148600   Tirante T. A.         2                  5              0.640000
148601    Mannarino A.         3                  5              0.347826
148602       Gorzny S.         3                  5              0.481481
148603    Collignon R.         2                  5              0.384615
148604    Michelsen A.         3                  3              0.666667
148605         Cina F.         0                  3              0.576923
148606        Vukic A.         2                  5              0.652174
148607     Sakamoto R.         3                  5              0.666667

In [88]:
home_game_counts = completed_matches[[
    "match_id",
    "home_games_won",
    "total_games"
]].copy()

home_game_counts = home_game_counts.rename(columns={
    "home_games_won": "games_won"
})

home_history = home_history.merge(
    home_game_counts,
    on="match_id",
    how="left"
)

In [89]:
away_game_counts = completed_matches[[
    "match_id",
    "away_games_won",
    "total_games"
]].copy()

away_game_counts = away_game_counts.rename(columns={
    "away_games_won": "games_won"
})

away_history = away_history.merge(
    away_game_counts,
    on="match_id",
    how="left"
)

In [90]:
player_history = pd.concat(
    [home_history, away_history],
    ignore_index=True
)

player_history = player_history.sort_values(
    ["date_timestamp", "match_id"]
).reset_index(drop=True)

In [91]:
player_history[[
    "player_name",
    "games_won",
    "total_games"
]].head(10)

       player_name  games_won  total_games
0       Galovic V.       12.0         19.0
1        Dougaz A.        7.0         19.0
2      Sakamoto P.       12.0         27.0
3         Young D.       15.0         27.0
4       Escobar G.       16.0         35.0
5        Quiroz R.       19.0         35.0
6  Barrios Vera T.        8.0         20.0
7      Harrison C.       12.0         20.0
8      Oliveira G.       15.0         26.0
9         Draxl L.       11.0         26.0

In [92]:
player_history["games_won_pct_last_10"] = (
    player_history
    .groupby("player_id")
    .apply(
        lambda g: (
            g["games_won"].shift(1).rolling(10, min_periods=1).sum()
            /
            g["total_games"].shift(1).rolling(10, min_periods=1).sum()
        )
    )
    .reset_index(level=0, drop=True)
)

/var/folders/7t/s00qhkf90sdgwcv66lcjh2x40000gn/T/ipykernel_18511/1983688151.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

In [93]:
player_history[[
    "player_name",
    "games_won",
    "total_games",
    "games_won_pct_last_10"
]].tail(20)

           player_name  games_won  total_games  games_won_pct_last_10
148588     Monteiro T.       12.0         18.0               0.561702
148589    Coppejans K.        6.0         18.0               0.500000
148590     Petkovic M.       18.0         34.0               0.495575
148591       Torres T.       16.0         34.0               0.502024
148592     Vacherot V.       19.0         29.0               0.485816
148593    Kovacevic A.       10.0         29.0               0.465116
148594     Virtanen O.       22.0         53.0               0.533632
148595       Rublev A.       31.0         53.0               0.546468
148596  Varillas J. P.       12.0         19.0               0.507692
148597      Kumstat J.        7.0         19.0               0.592885
148598    Tsitsipas S.       23.0         40.0               0.514403
148599         Fils A.       17.0         40.0               0.608491
148600   Tirante T. A.       21.0         46.0               0.507634
148601    Mannarino A.       25.0         46.0               0.465438
148602       Gorzny S.       25.0         49.0               0.500000
148603    Collignon R.       24.0         49.0               0.449640
148604    Michelsen A.       18.0         23.0               0.542373
148605         Cina F.        5.0         23.0               0.532819
148606        Vukic A.       25.0         52.0               0.557018
148607     Sakamoto R.       27.0         52.0               0.543651

In [94]:
# Feature: Wins on hard surface
player_history["is_hard"] = (
    player_history["surface"].str.lower() == "hard"
).astype(int)

In [95]:
player_history["hard_win"] = (
    player_history["won"] * player_history["is_hard"]
)

In [96]:
player_history["previous_hard_wins"] = (
    player_history
    .groupby("player_id")["hard_win"]
    .transform(lambda s: s.shift(1).cumsum())
)

player_history["previous_hard_matches"] = (
    player_history
    .groupby("player_id")["is_hard"]
    .transform(lambda s: s.shift(1).cumsum())
)

In [97]:
player_history["hard_win_rate"] = (
    player_history["previous_hard_wins"]
    / player_history["previous_hard_matches"]
)

In [98]:
player_history[[
    "player_name",
    "surface",
    "won",
    "previous_hard_matches",
    "previous_hard_wins",
    "hard_win_rate"
]].tail(20)

,player_name,surface,won,previous_hard_matches,previous_hard_wins,hard_win_rate
148588,Monteiro T.,clay,1,66.0,27.0,0.409091
148589,Coppejans K.,clay,0,89.0,42.0,0.471910
148590,Petkovic M.,clay,1,4.0,2.0,0.500000
148591,Torres T.,clay,0,7.0,5.0,0.714286
148592,Vacherot V.,hard,1,101.0,63.0,0.623762
148593,Kovacevic A.,hard,0,270.0,157.0,0.581481
148594,Virtanen O.,hard,0,167.0,103.0,0.616766
148595,Rublev A.,hard,1,255.0,164.0,0.643137
148596,Varillas J. P.,clay,1,29.0,8.0,0.275862
148597,Kumstat J.,clay,0,7.0,3.0,0.428571
148598,Tsitsipas S.,hard,1,221.0,141.0,0.638009
148599,Fils A.,hard,0,152.0,95.0,0.625000
148600,Tirante T. A.,hard,0,97.0,56.0,0.577320
148601,Mannarino A.,hard,1,206.0,96.0,0.466019
148602,Gorzny S.,hard,1,12.0,6.0,0.500000
148603,Collignon R.,hard,0,105.0,63.0,0.600000
148604,Michelsen A.,hard,1,172.0,106.0,0.616279
148605,Cina F.,hard,0,59.0,35.0,0.593220
148606,Vukic A.,hard,0,245.0,134.0,0.546939
148607,Sakamoto R.,hard,1,105.0,62.0,0.590476

In [99]:
player_history

,match_id,date_timestamp,season_year,surface,player_id,player_name,opponent_id,opponent_name,winner_code,aces,...,games_won_pct,game_diff,games_won,total_games,games_won_pct_last_10,is_hard,hard_win,previous_hard_wins,previous_hard_matches,hard_win_rate
0,50962420,1609859400,2021,hard,479435,Galovic V.,283198,Dougaz A.,1.0,NaN,...,63.16,5.0,12.0,19.0,NaN,1,1,NaN,NaN,NaN
1,50962420,1609859400,2021,hard,283198,Dougaz A.,479435,Galovic V.,1.0,NaN,...,36.84,-5.0,7.0,19.0,NaN,1,0,NaN,NaN,NaN
2,41905728,1609862100,2021,hard,839524,Sakamoto P.,186820,Young D.,2.0,NaN,...,44.44,-3.0,12.0,27.0,NaN,1,0,NaN,NaN,NaN
3,41905728,1609862100,2021,hard,186820,Young D.,839524,Sakamoto P.,2.0,NaN,...,55.56,3.0,15.0,27.0,NaN,1,1,NaN,NaN,NaN
4,31331956,1609865100,2021,hard,814701,Escobar G.,338092,Quiroz R.,2.0,NaN,...,45.71,-3.0,16.0,35.0,NaN,1,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148603,14929371,1788196800,2026,hard,273841,Collignon R.,787151,Gorzny S.,1.0,13.0,...,48.98,-1.0,24.0,49.0,0.449640,1,0,63.0,105.0,0.600000
148604,96460674,1788199200,2026,hard,207923,Michelsen A.,639555,Cina F.,1.0,6.0,...,78.26,13.0,18.0,23.0,0.542373,1,1,106.0,172.0,0.616279
148605,96460674,1788199200,2026,hard,639555,Cina F.,207923,Michelsen A.,1.0,2.0,...,21.74,-13.0,5.0,23.0,0.532819,1,0,35.0,59.0,0.593220
148606,55918190,1788203100,2026,hard,444516,Vukic A.,852781,Sakamoto R.,2.0,22.0,...,48.08,-2.0,25.0,52.0,0.557018,1,0,134.0,245.0,0.546939
148607,55918190,1788203100,2026,hard,852781,Sakamoto R.,444516,Vukic A.,2.0,38.0,...,51.92,2.0,27.0,52.0,0.543651,1,1,62.0,105.0,0.590476

In [100]:
# Performance features
performance_features = [
    "win_rate_last_10",
    "avg_aces_last_10",
    "avg_double_faults_last_10",
    "avg_service_points_won_last_10",
    "avg_return_points_won_last_10",
    "avg_break_points_won_last_10",
    "avg_break_points_saved_last_10",
    "sets_won_pct_last_10",
    "games_won_pct_last_10",
    "hard_win_rate"
]

In [101]:
# Checking whether a given player is home player
match_home_ids = completed_matches[[
    "match_id",
    "home_id"
]].copy()

In [102]:
player_history = player_history.merge(
    match_home_ids,
    on="match_id",
    how="left"
)

In [103]:
player_history["is_home"] = (
    player_history["player_id"] == player_history["home_id"]
)

In [104]:
player_history[[
    "match_id",
    "player_name",
    "player_id",
    "home_id",
    "is_home"
]].head(10)

   match_id      player_name  player_id  home_id  is_home
0  50962420       Galovic V.     479435   479435     True
1  50962420        Dougaz A.     283198   479435    False
2  41905728      Sakamoto P.     839524   839524     True
3  41905728         Young D.     186820   839524    False
4  31331956       Escobar G.     814701   814701     True
5  31331956        Quiroz R.     338092   814701    False
6  20264415  Barrios Vera T.     376007   376007     True
7  20264415      Harrison C.     884091   376007    False
8  60708459      Oliveira G.     303110   303110     True
9  60708459         Draxl L.     806525   303110    False